### ISSUE TITLE
Background Color for RoundRect Mode

### ISSUE THREAD

**Issue by fabianpimminger** [kitasuke/PagingMenuController#100]
Hi,

thanks for making this component. I'm currently building an app where I would want to customize the background of the MenuView while using RoundRect items. 

Example:

![bildschirmfoto 2015-10-17 um 21 31 31](https://cloud.githubusercontent.com/assets/45733/10560800/7655e7d4-7516-11e5-9b3a-b54330f41857.png)

I've made the customization in a fork and would like to know if I should submit a pull request or if you are seeing any issues with colored backgrounds and RoundRect items?

https://github.com/fabianpimminger/PagingMenuController/commit/5a25f760db9724f0b3864db784b9d413cab6cf23

**Comment by kitasuke** [comment]
I welcome your pull request!
I was having some problems with touch detect on menu view, but it was fixed the other day.
No need to set clear color explicitly any more.
