### ISSUE TITLE
CollectionView ReloadData bug

### ISSUE THREAD

**Issue by wraithseeker** [kitasuke/PagingMenuController#102]
There's a bug with the usage of CollectionView and PagingMenuController with the reloading of the CollectionView affecting user experience.

Setup
Initial ViewController with a CollectionView
Second ViewController that shows an enlarged Image 

Using JTSImageViewController to show enlarged image.

This issue can be replicated by showing the second VC and when it is dismissed, the CollectionView in the initial VC is reloaded

**Comment by wraithseeker** [comment]
My previous version with PagingMenuController at https://itunes.apple.com/ca/app/dota2-art-wallpapers-heroes/id1045660127?mt=8 has no issues.

Is there any new updates that caused this bug or could this be a bug from Apple?

**Comment by kitasuke** [comment]
Which version of PagingMenuController are you using?

**Comment by wraithseeker** [comment]
The newest version. I no longer have a copy of the live app. I think it could also be because Apple changed something?

**Comment by kitasuke** [comment]
Well, this library's loading system has recently changed drastically to ensure better memory management. So it could be my fault depends on what version you used with your previous app.
However, since iOS 9 has released, Apple might change something related to UICollectionView.

> This issue can be replicated by showing the second VC and when it is dismissed, the CollectionView in the initial VC is reloaded
Do you mean you deleted second menu tab associated with second VC, then the initial VC is reloaded?

**Comment by wraithseeker** [comment]
I didn't change anything to the menu, here is how it goes in my app.

Tab 1(Initial) & 2 are both UIViewControllers with CollectionViews that display images. Their data is retrieved from a JSON endpoint online.

To replicate the issue. I load the app and click on one of the images. This brings up another view or ViewController.

 I dismiss it and I get sent back to Tab 1 which is my initial ViewController and it triggers a reloading of the view or the CollectionView.

**Comment by kitasuke** [comment]
Got it. This might be because of my fault. I'll fix it and let you know once I found out something.
Sorry for my inconvenience.

**Comment by kitasuke** [comment]
I've fixed it!
Can you try with the newest version 0.7.2?

**Comment by wraithseeker** [comment]
I tried it and it is fixed! Thanks!　ありがとうございます。

**Comment by kitasuke** [comment]
:smile:
