### ISSUE TITLE
UI testing

### ISSUE THREAD

**Issue by kitasuke** [kitasuke/PagingMenuController#110]
- Reduce future bugs
- Maintain stable state easily

**Comment by wraithseeker** [comment]
Hey! I noticed not long ago that although the UICollectionView refreshing bug is fixed, the page view tab which contains the title will refreshes itself still, is this working as intended?

**Comment by kitasuke** [comment]
Hi @wraithseeker. 
This issue is about UI Testing support by Xcode7. If you find some existing bugs, please open as a new issue.
It would be great if you could mention both what's your problem and what you expected.
