### ISSUE TITLE
Calling `rebuild` method causes crash

### ISSUE THREAD

**Issue by kitasuke** [kitasuke/PagingMenuController#113]

**Comment by patricks** [comment]
+1

**Comment by patricks** [comment]
It looks like #131 fixes the problem.

**Comment by kitasuke** [comment]
If you don't change `menuDisplayMode`, yes. However it still crashes with specific options.
I'll check all the conditions later.

**Comment by patricks** [comment]
Any improvements yet?

**Comment by kitasuke** [comment]
Sorry for slow progress. I was so busy with my work...
I'll be able to restart working on this issue soon.

**Comment by patricks** [comment]
Thx!
Currently the Library crashes on Line 62 in the ```MenuView``` class. If I call ```rebuild``` method

**Comment by patricks** [comment]
My pull request #140 fixes a few crashes.

**Comment by kitasuke** [comment]
#141 looks good! I can merge it if you reopen it.

**Comment by patricks** [comment]
#141 is open, I only closed #140

**Comment by kitasuke** [comment]
Sorry, I misunderstood!
