### ISSUE TITLE
Public Read Only Properties

### ISSUE THREAD

**Issue by souzainf3** [kitasuke/PagingMenuController#124]
Some properties could be for public access:

```swift

   // I might want to access a view controller through the index
    private(set) var pagingViewControllers = [UIViewController]() 

    private(set) var menuView: MenuView!
    private(set) var visiblePagingViewControllers = [UIViewController]()
    private(set) var currentPage: Int = 0
    private(set) var currentViewController: UIViewController!
```

The PagingMenuControllerDelegate protocol should inform the index and view controller which is being displayed.

**Comment by kitasuke** [comment]
The delegate protocol currently informs the index. I'll fix it to inform view controller as well.
However, I won't make these properties public, cause I don't think it's necessary.
Is there any specific reasons to access to these properties?

**Comment by souzainf3** [comment]
Public to read, yes, there is need for some cases.

The behavior should be similar to the UITabBarController. Developers with more advanced requirements are limited to current implementation. It was my case. Another problem is the life cycle of the displayed controllers.

I will make a fork, will perform these changes and make a pull request.

Thanks

**Comment by kitasuke** [comment]
Got it. Then getters of these properties could be public, not setters as well.

**Comment by kitasuke** [comment]
What do you think this change #125 , @souzainf3 ?

**Comment by souzainf3** [comment]
It was great that implementation. Thus, the component was not limited but do not let inexperienced programmers to run free with modifications.

I personally take care when using the flag +final in class, it will prevent that a developer on your need (we do not know what it is) subclassei it. If your desire (and I recognize that is noble) is to prevent developers change something that jeopardize the operation or even create bugs, then I recommend you use the flag (+final) only on certain properties or functions which can not be overridden.

Congratulations.

**Comment by kitasuke** [comment]
Thanks for your suggestions!
It's so much helpful and you made this library better.
I really appreciate it.
