### ISSUE TITLE
Cannot load underlying module for PagingMenuController

### ISSUE THREAD

**Issue by tonespy** [kitasuke/PagingMenuController#127]
I can't import `PagingMenuController` module into my project. It keeps giving me Cannot load underlying module in PagingMenuController. I install the module using Cocoapods `pod "PagingMenuController"` please help me out. What am I doing wrong?

**Comment by kitasuke** [comment]
Can you try this one?
https://github.com/Alamofire/Alamofire/issues/122

Just `Build` once.

**Comment by tonespy** [comment]
Well, that's surprising, it works now. Thanks
