### ISSUE TITLE
Could you add MenuScrolling option in Infinite mode ?

### ISSUE THREAD

**Issue by nashirox** [kitasuke/PagingMenuController#128]
Thanks in advance for developing very useful library.

I hope Infinite mode can scroll own menu like mercari.

Please consider to adding that option.

**Comment by kitasuke** [comment]
It's on to-do list.
I'll let you know once it's done.

**Comment by nashirox** [comment]
thx a lot !!

**Comment by kitasuke** [comment]
Sorry for kept you waiting so long.
Now menu scroll is supported for Infinite mode.
Please use 0.9.0.
