### ISSUE TITLE
why can't I update the Title of UIButton or other UIComponents using code when their ViewController is setted up by PagingMenuController?  

### ISSUE THREAD

**Issue by erinvilair** [kitasuke/PagingMenuController#129]
I created a father View Controller and a container View Controller in it as the PagingMenuController in Storyboard, and created two children View Controllers in Storyboard as well. I setup paingMenuController with the two children View Controllers. 
When I change the title or text of UIButton or UILabel or other UIComponents of the child View Controller with code, they still stay the same as the initial text when they created in Storyboard , nothing changed. It  seems the PagingMenuController makes them unchangeable, how can I change them? Is their some setting of PagingMenuController that I can modify to make them changeable?

**Comment by erinvilair** [comment]
P.S. the title of UIButton in father View Controller is unchangeable as well. the container view controller of  the father view controller is the pagingMenuController.

**Comment by kitasuke** [comment]
`rebuild` method can be used in this case. However, this method has some bugs at this moment.
Please wait for it's fixed.

**Comment by erinvilair** [comment]
Thanks for your help!

**Comment by kitasuke** [comment]
Sorry for late response, but it supports dynamic changing system with the latest version.
Call `setup` method with the new options. `rebuild` method is deleted.
