### ISSUE TITLE
Getting error in CAPSPageMenu.Swift

### ISSUE THREAD

**Issue by anuragvijayvergia** [kitasuke/PagingMenuController#132]
I am getting error as I add CAPSPageMenu.swift file to my project 

1) required public init?;?(coder aDecoder: NSCoder)  :  Expected '(' for initializer parameters
2)  required public init?;?(coder aDecoder: NSCoder) : Expected declaration
3) self.init(viewControllers:viewControllers, frame:frame, options:nil) :  Value of type '_ -> _' has no member 'init

Can any one provide me some info on this how to rectify this and use the page Menu library .

**Comment by kitasuke** [comment]
You posted on wrong place.
Ask about CAPSPageMenu.swift at PageMenu library page.
