### ISSUE TITLE
How to move programmatically to a tab?

### ISSUE THREAD

**Issue by antoineF** [kitasuke/PagingMenuController#136]
Hello, 

I want to move to a tab programmatically, how I can do it?
I can move the menu with the ```moveToMenu``` method but the method ```moveToMenuPage``` in the PagingMenuController is private. Is there an other way to do it?

Thanks.

**Comment by hunterlins** [comment]
Hi,
If possible can you code out the entire usage of this- I can't get in working either.

Thanks

**Comment by kitasuke** [comment]
There isn't other way at this moment. I'll support that usage.

**Comment by hunterlins** [comment]
Thanks for looking into this- if possible could you make a simple example showing from initialisation to actually calling the method? 

Thanks again for your help

**Comment by antoineF** [comment]
Ok thanks

**Comment by huchenme** [comment]
+1, need this

**Comment by kitasuke** [comment]
It's now supported.
Please use the latest version which is 0.7.7!

If there is something wrong, please reopen this or create a new one.

**Comment by huchenme** [comment]
Can you update README please?

**Comment by kitasuke** [comment]
Done!
https://github.com/kitasuke/PagingMenuController/blob/master/README.md#moving-to-a-menu-tag-programatically

**Comment by hunterlins** [comment]
Thanks for this!
