### ISSUE TITLE
Error running Example project

### ISSUE THREAD

**Issue by huchenme** [kitasuke/PagingMenuController#137]
<img width="1118" alt="screen shot 2015-12-17 at 10 08 23 pm" src="https://cloud.githubusercontent.com/assets/2078389/11871467/b91d27b6-a50a-11e5-8ec6-950e2f4f6b7e.png">

**Comment by kitasuke** [comment]
Did you run `pod install` in terminal?

**Comment by huchenme** [comment]
yes I do

**Comment by kitasuke** [comment]
Then, can you clean Xcode?

**Comment by velikanov** [comment]
I did run `pod install` but Product->Run is disabled…

**Comment by kitasuke** [comment]
Either of `PagingMenuControllerDemo` or `PagingMenuControllerDemo2` target should be chosen for demo project. Which target was chosen?

**Comment by kitasuke** [comment]
Please reopen this issue if it still happens.
