### ISSUE TITLE
How can i use it for dynamic page views ?

### ISSUE THREAD

**Issue by mohanmoorthy** [kitasuke/PagingMenuController#139]
Hi, My home viewcotroller consume data from web server and build the pages dynamically (Async call). Based on the web service response only I am going to setup the pagingmenu. Is it possible ? ( It works if I call the api in some other controller and pass it to homeview controller but I need it in home page only). Thank you for your great library :).

**Comment by patricks** [comment]
Hi,

there is a method named. ```rebuild(viewControllers, options: options)```
You can use it like the ```setup(viewControllers: viewControllers, options: options)``` method.
So if your pages are loaded from the web service you an call the ```rebuild()```method.

**Comment by mohanmoorthy** [comment]
Wow. That would be great. Really appricite you help. Thank you very much.

**Comment by CoderPug** [comment]
Related : [#77](https://github.com/kitasuke/PagingMenuController/pull/77)  #248
