### ISSUE TITLE
App terminated due to memory error

### ISSUE THREAD

**Issue by mohanmoorthy** [kitasuke/PagingMenuController#146]
I have used 15 menu in my app. When I  keep scrolling the menu app was leaking memory continuously and finally crashed. Anyway to deinit the created view controllers ? ( I have tried the all MenuDisplayModes and result was same).

**Comment by mohanmoorthy** [comment]
It was my fault. I used mkmapview in all my VC's. It consume more resource and threw me the memory leak. It's was fixed by setting mkmapview to nil.

**Comment by kitasuke** [comment]
Good to heat that!
