### ISSUE TITLE
Dynamic tab load with Storyboard crashes

### ISSUE THREAD

**Issue by saraht129** [kitasuke/PagingMenuController#147]
Hi, I'm using Storyboard to initialise PagingMenuController, and I only run `setup(viewControllers, options)` after an asynchronous request. This leads to a crash in `viewDidAppear` because when Storyboard initialized, the PagingMenuController has an empty `pagingViewControllers`. Is this a bug? Should PagingMenuController be checking its child view controllers before proceeding?

I'm able to fix this by adding the PagingMenuController programatically during the asynchronous return, but since the Storyboard way is in one of your official instructions, I'm thinking wouldn't it be best to allow such scenario in your library?

Thanks, and this is the best Pager library I've found so far :)

**Comment by kitasuke** [comment]
Thank you for using it.
Could you show me your code using `PagingMEnuController` if possible?
It would be easier to find out what's wrong.

**Comment by saraht129** [comment]
I added the PagingMenuController in the container view of my view controller in storyboard, and on `viewDidLoad ()`, I do the following:

        DataRequester.sharedInstance.getCategories({ (results) -> Void in
            if let catCount = results?.count {
                 PagingMenuController
                var vcList = [PostCollectionViewController]()
                for index in 0...catCount-1 {
                    let vc = PostCollectionViewController()
                    vc.title = results?[index].name
                    
                    vcList.append(vc)
                }
                
                self.setupPagingMenuController(vcList)
            }
            
            }) { (error) -> Void in
                print("Error: \(error.localizedDescription)")
        }

As you can see, I only provide `PagingMenuController` the `vcList` after the asynchronous return. When the `PagingMenuController` loads from storyboard, the `pagingViewControllers` is `nil`.

**Comment by kitasuke** [comment]
Are you done with this?

> You should add ContainerView into your view controller's view and set PagingMenuController as the embedded view controller's class

https://github.com/kitasuke/PagingMenuController#using-storyboard

**Comment by saraht129** [comment]
Yes I did. The PagingMenuController initialized correctly. If I run ` pagingMenuController.setup(viewControllers: vcList, options: options)` immediately on `viewDidLoad`, everything works fine.

**Comment by kitasuke** [comment]
It can be reproduced in my project. I'm fixing this issue.

**Comment by kitasuke** [comment]
Please use the latest version.
Feel free to reopen this issue if you still see the crash.

**Comment by saraht129** [comment]
Just had the time to test it, it works fine now :) Thanks for the fix!

**Comment by thihaaung6245** [comment]
@saraht129 , if the one you are trying now which perform dynamic menu base on server response. Any help with that by sharing example project or just some logic? I am also trying to do the same thing. Example project will be a lot helpful. Thanks
