### ISSUE TITLE
Any way to align the first menu item to left and rest items center ?

### ISSUE THREAD

**Issue by mohanmoorthy** [kitasuke/PagingMenuController#150]
![screen-shot-2016-01-22-at-7 19 27-pm](https://cloud.githubusercontent.com/assets/4567178/12512392/230a1c5c-c13e-11e5-8611-1e34be435728.png)

I need all the menu items displayed on center except the first item. If I set "centerItem: true" an empty space appeared in left side. Is it possible to remove it ?

**Comment by kitasuke** [comment]
Is `Infinite` MenuDisplayMode what you want?

**Comment by mohanmoorthy** [comment]
Thank you for your response. Infinite method is good way though but I would like to same behaviour in 
Standard mode. End up with little hack with your code works with my requirement

Edited 

private func targetContentOffsetX() -> CGFloat {

        switch options.menuDisplayMode {

        case let .Standard(_, centerItem, _) where centerItem:

            if(currentPage == 0) {

                return contentOffset.x

            } else {

                return centerOfScreenWidth()

            }

        case .SegmentedControl:

            return contentOffset.x

        case .Infinite:

            return centerOfScreenWidth()

        default:

            return contentOffsetXForCurrentPage()

        }

    }
