### ISSUE TITLE
Could not cast value of type UIViewController to Test.PagingMenuController

### ISSUE THREAD

**Issue by Lithium-HD** [kitasuke/PagingMenuController#151]
I'm trying to use this control in my test project:

I get this error : "Could not cast value of type UIViewController to Test.PagingMenuController" In the example it works fine. but in my test project I get error on this line:

let pagingMenuController = self.childViewControllers.first as! PagingMenuController

in front of this line I see this message too: 'Thread 1: SIGABRT'

how can I fix this?

**Comment by kitasuke** [comment]
Are you done with this in your test project?

> You should add ContainerView into your view controller's view and set PagingMenuController as the embedded view controller's class

https://github.com/kitasuke/PagingMenuController#using-storyboard

**Comment by Lithium-HD** [comment]
I don't know how to do this part you said: "and set PagingMenuController as the embedded view controller's class" 
I have ContainerView in my viewController. here's a screenshot from my storyboard

![1111](https://cloud.githubusercontent.com/assets/14963386/12638842/68ef54a0-c5b5-11e5-938f-bc7d6896cb5d.PNG)

**Comment by kitasuke** [comment]
<img width="909" alt="screen shot 2016-01-28 at 12 29 06 am" src="https://cloud.githubusercontent.com/assets/1732312/12639007/37944370-c556-11e5-9228-447e789da1b4.png">

**Comment by kitasuke** [comment]
Should be like above. A container has an embedded view controller which is right one in this case. You have to set its class as PagingMenuController.

**Comment by Lithium-HD** [comment]
wow, thanks. that was my mistake. it works like a charm now :)

**Comment by kitasuke** [comment]
:smile:

**Comment by Lithium-HD** [comment]
by the way, the pod's not working (it says unable to find 'PagingMenuController'. I added the classes manually (4 classes of paging controller)
I'd be grateful if you take a look at it.
thanks again :+1:

**Comment by kitasuke** [comment]
If I'm right, I believe that it was because of GitHub's server down a few hours ago.
CocoaPods is dependant on GitHub.
Thanks for informing :)

**Comment by Raviojha62** [comment]
Getting same problem  but i am getting in console like below
Could not cast value of type 'PagingMenuController.PagingMenuController' (0x1102740) to 'AppName.PagingMenuController' (0x3cb240).

**Comment by kitasuke** [comment]
This example project explains more detail. Please see the code.
https://github.com/kitasuke/PagingMenuController/tree/master/Example/PagingMenuControllerDemo
