### ISSUE TITLE
Usage of PagingMenuController inside of UINavigationController with translucency

### ISSUE THREAD

**Issue by SiNBizkit** [kitasuke/PagingMenuController#155]
I want to use PagingMenuController, but I have one issue. I add PagingMenuController inside of UINavigationController with true translucency value. Inside of PagingMenuController I use UIScrollView with vertical insets. That way my menu is hidden behind NavigationBar. How can I set some kind of vertical inset for MenuView only?

**Comment by kitasuke** [comment]
Could you show me your codes if possible?

**Comment by SiNBizkit** [comment]
@kitasuke of course!

```swift
//MARK: Initializing - viewDidLoad
pagingMenu_ = PagingMenuController(viewControllers: [UIViewController()])
addChildViewController(pagingMenu_)
view.addSubview(pagingMenu_.view)
pagingMenu_.didMoveToParentViewController(self)
```

I'm using Cartography extension as AutoLayout assistant
```swift
constrain(pagingMenu_.view) { view in
let superview = view.superview!
    view.leading == superview.leading
    view.bottom  == superview.bottom
    view.trailing == superview.trailing
}
```

But I as know I can't use topLayoutGuide with Cartography explicitly. That's why I set the constraint manually
```swift
topLayoutGuide.bottomAnchor.constraintEqualToAnchor(
	pagingMenu_.topLayoutGuide.topAnchor).active = true
```

Everything looks fine, MenuView locates below NavigationBar. But content of my inner controller is clipping on top during vertical scrolling. Maybe I do it wrong, I'm developing on iOS not so long.
I would be really appreciate for your help.

**Comment by kitasuke** [comment]
This could be workaround for that case.

```
let pagingMenuController = PagingMenuController(viewControllers: viewControllers, options: options)
pagingMenuController.view.frame.origin.y += 64
pagingMenuController.view.frame.size.height -= 64
```

Could you try this one?

**Comment by kevinlee85** [comment]
@kitasuke Your workaround sometimes may not work perfectly. Have you found the real solution for this? THANK YOU.
