### ISSUE TITLE
Image view instead of label for menu title

### ISSUE THREAD

**Issue by narasimhanallamsetty** [kitasuke/PagingMenuController#156]
Hi, I am using pagingMenu in my application. In my application instead of title label for menu item I need to use image views. How can I achieve this?

Please let me know where I need to do changes. Currently we are using UILabel for menu title. I need to use image in the place of label. Thank you in advance. Let me know if you need more information.

**Comment by kitasuke** [comment]
Currently its not possible. I'll look into if I can provide any options for that.

**Comment by jaytrixz** [comment]
+1 on this feature request as well

**Comment by TuongVu** [comment]
I love your library..Please implement this feature.

**Comment by SuYungCheng** [comment]
I love your library, too. And +1 on this feature.Thanks!

**Comment by htarwara6245** [comment]
+1 on that feature.I will be great if we add image on left side or label title

**Comment by raulastu** [comment]
any update ?? waiting for it before I embark on building my own

**Comment by baquiax** [comment]
Hi @raulastu! I have made a fork and implement it in my repo!
I do not sent the pull request to the official repository because I'm not sure if it is the best way to do it. So I need feedback.

[Check it here!](https://github.com/baquiax/PageMenu/commit/6f410389b7a44b176b907f2ccf59779bce6f24d4)

**Comment by kitasuke** [comment]
It's almost done, but I'm thinking about the best way to pass images.
There might be an option to choose text or image for MenuView.

**Comment by TuongVu** [comment]
What's the status on the feature?

**Comment by spsammy-symbio** [comment]
+1 for me too.

**Comment by kitasuke** [comment]
Current progress is same as before, but it'll be done soon.

**Comment by kitasuke** [comment]
0.10.0 with this feature will be released soon.

**Comment by kitasuke** [comment]
Please use 1.0.0 version.
