### ISSUE TITLE
Access to previous viewcontroller

### ISSUE THREAD

**Issue by sirvine** [kitasuke/PagingMenuController#157]
I have some small teardown that I would like to introduce when the page is changed. 

I think I need to use `willMoveToMenuPage` for this purpose. However, this delegate method only returns the current page, which is actually the target page, not the departing page. Also, I don't see any public API for determining the direction of movement, which makes it hard to find the previous ViewController from only knowing the target.

**Comment by kitasuke** [comment]
Alright, I'll make it accessible.

**Comment by mitchellporter** [comment]
+1 would love access to both the previous vc and the current vc.

I think it should be fairly easy to add, I remember playing around with it a couple weeks ago, but I just hacked it together so nothing good enough for a proper pull request.

**Comment by kitasuke** [comment]
What do you think about this PR, @sirvine, @mitchellporter?

**Comment by sirvine** [comment]
Looks good for my purposes. Thanks!

**Comment by kitasuke** [comment]
I'm gonna go with this change.
This will be merged soon, there are a few things to be fixed though.
