### ISSUE TITLE
Customizing the PageMenuView background?

### ISSUE THREAD

**Issue by htarwara6245** [kitasuke/PagingMenuController#158]
How to customize page menu background same as parent view background?

Parent View (which use PagingMenu Container ) -> 2 child segment control menu view.
If I can set parent view background which display menu,how to set background color as parent view in this menu items background because when i set the background color,it only set the same color as parent on its selected.

Any help?

**Comment by kitasuke** [comment]
I'll look into more detail to make sure if it's possible.
I'll post updates here.

**Comment by kitasuke** [comment]
Please use 1.0.0 version.
