### ISSUE TITLE
3D touch support for embedded view controller 

### ISSUE THREAD

**Issue by bharatkrishna** [kitasuke/PagingMenuController#160]
I have PagingMenuController with table view controllers as child views. 
I've added 3D touch support for one of the child table views by implementing UIViewControllerPreviewingDelegate. But PagingMenuController doesn't seem to register the force touch. When I bypass the PagingMenuController and directly view the tableview, I am able to activate pop & peek for the table view cell. 

I added an extension to PagingMenuController to implement the UIViewControllerPreviewingDelegate. With this I can get it to pop but I am not able to access the cell which was pressed. Hence I am not able to populate the view in pop with data from the selected cell.

**Comment by bharatkrishna** [comment]
I was able to achieve this by adding an extension as follows:

```
extension PagingMenuController: UIViewControllerPreviewingDelegate {
    public func previewingContext(previewingContext: UIViewControllerPreviewing, viewControllerForLocation location: CGPoint) -> UIViewController? {

        guard let destinationViewController = self.storyboard?.instantiateViewControllerWithIdentifier("AddItemView") as? ItemAddViewController else { return nil }
        
        let ItemsViewController = self.pagingViewControllers.first as! ItemsViewController 
        
        guard let indexPath = ItemsViewController.tableView.indexPathForRowAtPoint(location),
            cell = ItemsViewController.tableView.cellForRowAtIndexPath(indexPath) else { return nil }

        let ItemObject = ItemsViewController.fetchedResultsController.objectAtIndexPath(indexPath)
        
        destinationViewController.Item = ItemObject as? Item
        
        destinationViewController.preferredContentSize = CGSize(width: 0, height: 0)
        
        previewingContext.sourceRect = cell.frame
        
        return destinationViewController
    }
    
    public func previewingContext(previewingContext: UIViewControllerPreviewing,
        commitViewController viewControllerToCommit: UIViewController){
            self.navigationController!.showViewController(viewControllerToCommit,sender:self)
    }
}
```

**Comment by kitasuke** [comment]
Good point. We should support 3D touch in this library. Thanks for your info!

**Comment by bharatkrishna** [comment]
It'll be helpful if PagingMenuController passed on touches to the view it is currently displaying. With the approach I've mentioned in my previous comment, only of the views can get 3D touch. This doesn't scale to all tabs :disappointed:

**Comment by kitasuke** [comment]
This should be done by your side, so I close this issue.
