### ISSUE TITLE
Tapped status bar, but didn't scroll to top

### ISSUE THREAD

**Issue by yo1106** [kitasuke/PagingMenuController#181]
I set false to scrollsToTop, current page excepting.
But don't scroll to top.

- ver 0.8.0 is don't move
- ver 0.7.8 is move

![2016-04-05 19 43 42](https://cloud.githubusercontent.com/assets/2725669/14279411/0a4588e6-fb68-11e5-87c0-365f4bc29f43.png)

**Comment by AleksandarPetrov** [comment]
You can try something like that

`
func didMoveToPageMenuController(menuController: UIViewController, previousMenuController: UIViewController) {
        if let pagingMenuController = self.childViewControllers.first as? PagingMenuController {
            for controller in pagingMenuController.visiblePagingViewControllers {
                for subview in controller.view.subviews {
                    if let scrollView = subview as? UIScrollView {
                        scrollView.scrollsToTop = false
                    }
                }                
            }
            
            for subview in menuController.view.subviews {
                if let scrollView = subview as? UIScrollView {
                    scrollView.scrollsToTop = true
                }
            }
        }
    }
`

**Comment by yo1106** [comment]
Thank you.

I missed that the delegate method was changed

```swift
    func didMoveToMenuPage(page: Int) {
    }
```

```swift
    func didMoveToPageMenuController(menuController: UIViewController, previousMenuController: UIViewController) {
    }
```
