### ISSUE TITLE
willMoveToPageMenuController returns the same previous and new VC in 0.9

### ISSUE THREAD

**Issue by nickdnk** [kitasuke/PagingMenuController#193]
Hello

After updating to 0.9, I had some issues with this project. It seems that the willMoveToPageMenuController method now returns the same object for previousMenuController and menuController, leading to a lot of problems. Both these pointers reference the previousMenuController, so you don't have any access to the new one with this method. I downgraded to 0.8 and now everything is dandy.

**Comment by kitasuke** [comment]
Oh sorry, it's a bug. I'm working on the bug fix.

**Comment by kitasuke** [comment]
Fixed version(0.9.1) has just released. Please use the latest one.
Sorry for my inconvenience :(
