### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by lilpennyjr** [kitasuke/PagingMenuController#2]
I installed the PagingViewMenu through CocoaPods and followed the instructions, but overtime I build and run the program I get the "fatal error: unexpectedly found nil while unwrapping an Optional value" and it points to line 40  "self.menuView.moveToMenu(page: currentPage, animated: false)" in PagingMenuController. How do I fix this issue?

**Comment by kitasuke** [comment]
@lilpennyjr Thanks for using it. 
I'm gonna look into some codes around there. I'll update here once I find out something wrong.

**Comment by kitasuke** [comment]
@lilpennyjr Can you post your code about how your project is using PagingMenuController? Or could you some questions below?
- Storyboard based layout?
- Which orientation?
- Which `menuDisplayMode` in `PagingMenuOptions` ?

**Comment by kitasuke** [comment]
Please reopen this issue if you catch the error again.

**Comment by tcitry** [comment]
Here I have the same problem.
```bash
fatal error: unexpectedly found nil while unwrapping an Optional value
```
![image](https://cloud.githubusercontent.com/assets/5220740/9440781/5de9da80-4aa4-11e5-8b46-a933f5276010.png)

**Comment by kitasuke** [comment]
@tcitry Can you give me which version of Swift and PagingMenuController you are using?

**Comment by tcitry** [comment]
@kitasuke sure
Xcode Version 6.4 (6E35b)
Apple Swift version 1.2 (swiftlang-602.0.53.1 clang-602.0.53)
The last version of PagingMenuController
