### ISSUE TITLE
[要望]それぞれのメニューの上をカスタマイズしたい。

### ISSUE THREAD

**Issue by yukitoto** [kitasuke/PagingMenuController#204]
PagingMenuControllerをいつも活用させていただいております。

現在作成しているプロダクトにおいても利用させていただきたいと思っているのですが、メニューの上にCustom Viewを挿入することはできますか？
詳細をご説明すると、Standard modeを利用しているのですが、そのメニューを上から100pxのところにoriginのyを設定し、その上にimageViewを載せたいと思っています。それぞれのメニューでCustom Viewを設定できるようにしたいと考えています。
もしくは、メニューのoriginだけをずらし、その下に元々のスクロールビューを設置し、擬似的にCustomViewを配置できたらと考えています。
すでにそのような機能・もしくはカスタマイズ方法があればぜひ教えてもらいたいです。

拙い表現で大変心苦しいのですが、何卒よろしくお願いします。

**Comment by kitasuke** [comment]
imageViewにマージンを追加出来るようにするオプションだけではなく、Custom View自体も必要ということで認識あってますか？
他に優先度が高いバグ修正があるので時間はかかりますが、対応したいと思っています。

**Comment by yukitoto** [comment]
はい！そういうことですね。ぜひお願いしたいです。
ちなみにすでにPageごとにImageViewを設定することはできるのですか？そうだとしたら完全に勉強不足でした。申し訳ありません。

**Comment by kitasuke** [comment]
わかりました！
ImageViewはマスターにマージされてますが、まだリリースはしてないんですよ。ImageViewだけならマスターブランチ使って試せますが、Custom Viewも必要とのことなのでもう少しお待ちください。おそらくImage Viewを実装したやり方を適用できる気がします。

**Comment by kitasuke** [comment]
一旦、ImageViewを設定する機能だけリリースしました。
以下のようにUIViewControllerにUIImageをセット出来るプロパティを追加しています。
カスタムビューはこの後に対応予定です。

```
viewController.menuItemImgae = UIImage()
```

**Comment by kitasuke** [comment]
1.0.0をリリースしました。イメージやカスタムビューがセット可能になっています。それを使用してください。

**Comment by yukitoto** [comment]
素早い対応ありがとうございます！！
早速使ってみたいと思います！
