### ISSUE TITLE
Jumping from first to last page and vice versa

### ISSUE THREAD

**Issue by Zfr21** [kitasuke/PagingMenuController#205]
I'm having issue about loading storyboard UIViews to page while I'm jumping from 1 to 3(last page) and from 3 to 1

firstly it loads just white page and after UIView elements

how can I solve this issue?

Thanks...

**Comment by kitasuke** [comment]
What's your expected behaviour?

**Comment by Zfr21** [comment]
while swiping between each other there is no problem but jumping from 3 to 1 and vice versa but i don't want to see white screen because it is not good user experience

**Comment by kitasuke** [comment]
Ok, then what do you want to see?

**Comment by Zfr21** [comment]
I just want to see the ui elements directly without seeing white screen

**Comment by kitasuke** [comment]
Alright. I'll add `All` into `lazyLoadingPage` option so that white page isn't displayed anymore.

**Comment by Zfr21** [comment]
Thanks so much I'm w8 impatiently because i'll publish my app soon :)

**Comment by danielstorch** [comment]
I was wondering the same. Expected behavior would be to see every element inbetween. Like it's now, just instead of the white pages, the controllers with their content!

Great library! And thanks for the fast responses!

**Comment by kitasuke** [comment]
Please use 1.0.0 version.

**Comment by Zfr21** [comment]
gettin "Use of unresolved identifier 'PagingMenuOptions' " error after I updated to 1.0.0

let options = PagingMenuOptions()
    options.menuDisplayMode = PagingMenuOptions.MenuDisplayMode.SegmentedControl
    options.menuItemMode = PagingMenuOptions.MenuItemMode.None
