### ISSUE TITLE
Extranous argument label in .setup method

### ISSUE THREAD

**Issue by nickdnk** [kitasuke/PagingMenuController#217]
After upgrading to 0.10.1 I get a compile/build error when trying to Archive my app. It says I have an extranous argument label in my .setup method and suggests I remove `viewControllers:` - if I do, it suggests I add `viewControllers:`. I downgraded to 0.9.1 and now it works again.

I could build and run the app on simulator but not archive it. Very odd?

Method called like: `pagingMenuController.setup(viewControllers: vcs, options: options)`

Where `vcs` is an array of `UIViewController` and options is an instance of `PagingMenuOptions`.

**Comment by sucrewar** [comment]
Same whit me, if i have a custom class of type PagingMenuController i recived Extranous argument label in .setup method . if i use standartd PagingMenuController whitout a custom class its ok. I have updated to v0.10.1. when downgrade to 0.9.1 it´s ok.

**Comment by kitasuke** [comment]
Sorry for my inconvenience. I'll fix this as soon as possible.

**Comment by kitasuke** [comment]
`setup` method's label is changed, so it's strange that compiler suggests adding/removing `viewControllers:`.
Can you clean your project and delete DerivedData, then try again?

```
public func setup<Element : MenuControllerType>(menuControllerTypes: [Element], options: PagingMenuController.PagingMenuOptions)
public func setup<Element : MenuItemType>(menuItemTypes: [Element], options: PagingMenuController.PagingMenuOptions)
```

**Comment by sucrewar** [comment]
I clean derivedData and clean project and still prompt the same error

**Comment by kitasuke** [comment]
Can you share your code?

**Comment by sucrewar** [comment]
`import UIKit
import PagingMenuController


class MIPagingMenuController: PagingMenuController {

    

	var disabledButtons = [String]()
	var titleForShare = ""
	var contentForShare = ""


	override func moveToMenuPage(page: Int, animated: Bool) {

		if let pageTitle = self.pagingViewControllers[page].title {
			if disabledButtons.contains(pageTitle) {
				self.shareItem(MIHelper.htmlText2(contentForShare)!, link: "")
				return
			}
		}
		super.moveToMenuPage(page, animated: animated)
	}
}

class MIPagerForTrailsDetail: UIViewController,UIScrollViewDelegate, PagingMenuControllerDelegate, UIGestureRecognizerDelegate {

	var viewControllers = [UIViewController]()
	let pagingMenuOpts = PagingMenuOptions()
	var pagingMenuController: MIPagingMenuController?
	var trail: Trails! {
		didSet {
			self.trailHasChanged()
		}
	}
	var lastTrail: Trails?
	var loadingViewController: MILoadingViewController!


	override func viewDidLoad() {
		super.viewDidLoad()

		pagingMenuOpts.menuHeight = 44
		pagingMenuOpts.backgroundColor = UIColor.clearColor()
		pagingMenuOpts.selectedBackgroundColor = UIColor.clearColor()
		pagingMenuOpts.selectedTextColor = UIColor.darkGrayColor()
		pagingMenuOpts.menuItemMode = .Underline(height: 4, color: MIConstants.Colors.smiityBlue, horizontalPadding: 0, verticalPadding: 0)
		pagingMenuOpts.menuDisplayMode = .Standard(widthMode: .Flexible, centerItem: true, scrollingMode: .PagingEnabled)
		pagingMenuOpts.menuItemMargin = 10
		pagingMenuOpts.scrollEnabled = true


		if let font = UIFont(name: MIConstants.Font.icon, size: 22) {
			pagingMenuOpts.font = font
			pagingMenuOpts.selectedFont = font
		}

		self.loadingViewController = MILoadingViewController(nibName: "MILoadingViewController", bundle: nil)
		self.loadingViewController.title = "..."
		self.viewControllers.append(self.loadingViewController)
		self.pagingMenuController = MIPagingMenuController(viewControllers: self.viewControllers, options: self.pagingMenuOpts)
		self.displayContentController(self.pagingMenuController!)
		self.pagingMenuController!.delegate = self
	}




	func trailHasChanged() {

		var same = false
		if let last = self.lastTrail {
			same = (last == self.trail)
		}

		if !same {

			self.pagingMenuOpts.menuDisplayMode = .Standard(
				widthMode: .Flexible, centerItem: true, scrollingMode: .PagingEnabled
			)
			self.viewControllers = [self.loadingViewController]
			self.pagingMenuController!.setup(viewControllers: self.viewControllers, options: self.pagingMenuOpts)
			self.buildTabs(self.trail)
		}
	}

	func buildTabs (trail: Trails) {
		self.viewControllers.removeAll()

		let infoDescription = trail.content

		if infoDescription != "" {
			let infoVC = MIDescriptionViewController(nibName: "MIDescriptionViewController", bundle: nil)
			infoVC.title = MIConstants.Icons.info_ico
			infoVC.htmlBoby = infoDescription
			self.viewControllers.append(infoVC)
		}




		if let places = trail.valueForKey("places") {
			let mapView = MIMapForTrailsViewController(nibName: "MIMapForTrailsViewController", bundle: nil)
			mapView.title = MIConstants.Icons.pois_ico
			mapView.trails = places as? RLMArray
			self.viewControllers.append(mapView)
			//mapView.setRegion(Double(place.latForPlace)!, lng: Double(place.lngForPlace)!, span: 5.0, animation: true)
			//}
		}

		if	let images = trail.valueForKey("images") {
			let photoPager = MIGalleryCollectionViewController(nibName: "MIGalleryCollectionViewController", bundle: nil)
			photoPager.title = MIConstants.Icons.photos_ico
			var photos = [String]()
			for i in 0 ..< images.count {
				let photo = images.objectAtIndex(i) as! ImagesForTrails
				photos.append(photo.linkForImage)
			}
			photoPager.gallery = photos
			self.viewControllers.append(photoPager)
		}
		if	let video = trail.valueForKey("videos") {
			let videoPlayer = MIVideoPlayerViewController(nibName: "MIVideoPlayerViewController", bundle: nil)
			videoPlayer.title = MIConstants.Icons.video_ico
			videoPlayer.videos = video as? RLMArray
			self.viewControllers.append(videoPlayer)
		}
		let vc = UIViewController(nibName: nil, bundle: nil)
		vc.title = MIConstants.Icons.share_ico
		self.pagingMenuController?.disabledButtons.append(vc.title!)
		self.pagingMenuController?.titleForShare =  trail.title
		self.pagingMenuController?.contentForShare = trail.content
		self.viewControllers.append(vc)

		if viewControllers.count > 0 {
			self.pagingMenuOpts.menuDisplayMode = .SegmentedControl
			self.pagingMenuController!.setup(viewControllers: self.viewControllers, options: self.pagingMenuOpts)
		} else {
		}
	}

	override func didReceiveMemoryWarning() {
		super.didReceiveMemoryWarning()
		// Dispose of any resources that can be recreated.
	}

	func didMoveToPageMenuController(menuController: UIViewController, previousMenuController: UIViewController) {
		if self.pagingMenuController!.disabledButtons.contains(menuController.title!) {
			if let index =  self.pagingMenuController?.pagingViewControllers.indexOf(previousMenuController) {
				self.pagingMenuController!.moveToMenuPage(index, animated: true)
			}
		}
	}
}
`
now this code work whit version 0.9.1 but if i upgrade to version 0.100.1 the compiler prompt the error "Extranous argument label in .setup method"  in this part of code:
 `self.pagingMenuController = MIPagingMenuController(viewControllers: self.viewControllers, options: self.pagingMenuOpts)`

**Comment by kitasuke** [comment]
Thanks a lot! I'm investigating...

**Comment by sucrewar** [comment]
if you need more information please tell me . 
thanks :)

**Comment by nickdnk** [comment]
Hey

I just tried to just press "Build" in X-Code, and I get this error: 

Undefined symbols for architecture arm64:
  "PagingMenuController.PagingMenuOptions.__allocating_init () -> PagingMenuController.PagingMenuOptions", referenced from:
      Nyx.NewTableViewController.viewDidLoad () -> () in NewTableViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Where NewTableViewController is my own class of course, but clearly this has something to do with this library.

The odd thing is I can clean, archive and run the app. I just can't press "Build"? I tried deleting DerivedData folder as well.

**Comment by kitasuke** [comment]
Thanks for your info.
I almost found out the reason. I'm fixing this now.

**Comment by nickdnk** [comment]
Hey kitasuke!

Any news? It turns out my Release built version currently on the AppStore crashes now. I cannot build and test it on my device to see the crash dump, as I get the above error when building for device, but not for Simulator or Archiving. This is a really, really big problem! Help!

**Comment by nickdnk** [comment]
If I reinstall all pods, clean, etc., I get this error when building:
`...NewTableViewController.swift:10:8: Module file was created by an older version of the compiler; rebuild 'PagingMenuController' and try again:...`

**Comment by nickdnk** [comment]
Downgrading Cocoapods from 1.0.0 to 0.39.0, cleaning derived data, reinstalling all pods and using 0.8.0 of PagingMenuController fixed the problem, for now. So it seems the problem is related to the 1.0.0 version of CocoaPods somehow.

**Comment by kitasuke** [comment]
It's not CocoaPods issue.
Please use 0.9.1 version. Clean your project and delete derived data after downgrading this library to 0.9.1.

**Comment by nickdnk** [comment]
Okay. I will try that later. But what about the other problem in 0.9.1 ? The original problem with extranous label in setup?

**Comment by nickdnk** [comment]
Updating to 0.9.1 with Cocoapods 0.39.0 still works. So it just seems to break completely at 0.10.1.

**Comment by nickdnk** [comment]
And then we're back to the app crashing with this error:` fatal error: unexpectedly found nil while unwrapping an Optional value.
`
I have narrowed the problem down to this: I set an "`activeViewController`" instance variable based on the `willMoveToPageMenuController `delegate method. In 0.9.1, this is not called before you move page at least once, meaning that if you try to reference the *current* view controller without having moved any pages, it will be nil and the app crashes.

In 0.8.0 the `willMoveToPageMenuController `was called for initial presentation.
I tried "`didMoveToPageMenuController`" also. That is not called until the first move either.

You should change it so initial presentation calls "`didMoveToPageMenuController`" one time - i.e. "did move to first view controller".

**Comment by kitasuke** [comment]
> I have narrowed the problem down to this: I set an "activeViewController" instance variable based on the willMoveToPageMenuControllerdelegate method. In 0.9.1, this is not called before you move page at least once, meaning that if you try to reference the current view controller without having moved any pages, it will be nil and the app crashes.

`currentViewController` is set at the beginning. `nil` is set to it when you call `setup` method again, so it won't be `nil` when you access.
https://github.com/kitasuke/PagingMenuController/blob/0.9.1/Pod/Classes/PagingMenuController.swift#L188

**Comment by nickdnk** [comment]
Ah. Okay. It did not set that. Now I do
```
/* setup /*
activeViewController = pagingMenuController.currentViewController
```
It works now :)

**Comment by kitasuke** [comment]
Can you guys use the latest one, 0.10.2? It should be fixed now.

**Comment by nickdnk** [comment]
I'll have a look tomorrow. Thank you :)

**Comment by sucrewar** [comment]
thank you :)
