### ISSUE TITLE
How to use willMoveToPageMenuController to get page(int) like func willMoveToMenuPage?

### ISSUE THREAD

**Issue by SuYungCheng** [kitasuke/PagingMenuController#218]
I am a newbie in Swift.
I had used this function:
 func willMoveToMenuPage(page: Int)
It can get the page index.

If I use the new one:
func willMoveToPageMenuController(menuController: UIViewController, previousMenuController: UIViewController)

just can get the menuController and previousMenuController names.
print them like that:
<ProjectName.ControllerName : 0x7fbeb17d84e0>

And how to convert them to index?
Thanks!

**Comment by sucrewar** [comment]
you can check on your array of view controller by the name of view controller you want the index

**Comment by SuYungCheng** [comment]
Thanks! I use this Code below can show the VC index. But don't know if willMoveToPageMenuController better and easier than before function willMoveToMenuPage.

Is there any intention to change func  from willMoveToMenuPage to  willMoveToPageMenuController ?
```
func willMoveToPageMenuController(menuController: UIViewController, previousMenuController: UIViewController) {
        
        print(viewControllers.indexOf(menuController))
        
    }
```

**Comment by kitasuke** [comment]
Well, it might not be a better change for your case, but it covers some other cases as well.
Let me think about it anyway.

**Comment by SuYungCheng** [comment]
No disrespect.I just think in what situation that I can use.Your Pod is really good and many feature I need to study.^^

**Comment by SuYungCheng** [comment]
I found there are something strange in newest Pod.
I make 2 ViewControllers
It prints:
viewControllers=[<SidebarMenu.CollectScienceVC: 0x14c8aab50>, <SidebarMenu.CollectDiy2: 0x14c8ab5b0>]

And in didMoveToPageMenuController.I print menuController and previousMenuController. It looks like:
menuController=<SidebarMenu.CollectDiy2: 0x14c8ab5b0>
previousMenuController=<SidebarMenu.CollectScienceVC: 0x14c8aab50>
They are different.

But in willMoveToPageMenuController function, It looks like:
menuController=<SidebarMenu.CollectScienceVC: 0x14c8aab50>
previousMenuController=<SidebarMenu.CollectScienceVC: 0x14c8aab50>
There are all the same.

Is that right?

**Comment by kitasuke** [comment]
It's correct. It's fixed in master branch.

**Comment by kitasuke** [comment]
Please reopen this issue if you still see in the latest version.
