### ISSUE TITLE
Delegate methods for MenuView (without Controller)

### ISSUE THREAD

**Issue by MarcelStructr** [kitasuke/PagingMenuController#224]
I am trying out the new MenuView, which also works without enabling any Controller. Here's how I did it. 

http://www2.pic-upload.de/img/30723283/page1.jpg
http://www2.pic-upload.de/img/30723286/page2.jpg

The delegate methods didMoveToPageMenuController and willMoveToPageMenuController don't work here, though. I need delegate methods to know, if the MenuView got changed and which one is selected at the moment.

**Comment by MarcelStructr** [comment]
Hey @kitasuke , 
are there any problems? I could also try making them myself. But I don't know, if I am able to it and I am busy with my studies the next weeks.

**Comment by kitasuke** [comment]
This feature will be added, but please understand its not highest priority since there are some bug fixes to be done.

**Comment by kitasuke** [comment]
It's now fixed in master branch. I'll let you know once its released.

**Comment by kitasuke** [comment]
Please use 1.0.0 version.

**Comment by MarcelStructr** [comment]
Tried it out. Works really great! Also with two MenuViews at once, like in my example. 
Also the new way of using structs to define the Options is interesting.

Thank you for your work, @kitasuke
