### ISSUE TITLE
PagingMenuController menu behavior as navigationBar

### ISSUE THREAD

**Issue by acecilia** [kitasuke/PagingMenuController#225]
Hi there:

I am trying to use pagingMenuController menu in place of a navigationNar. When the phone rotates the navBar changes its height, so I need to change the pagingMenu menu's height. I tried changing the frame of the menuView property, but those changes are not being reflected in the view.

How can I achieve that?
Thanks!

**Comment by kitasuke** [comment]
Did you set menu view to `navigationItem.titleView`? If not, can you share your code?

**Comment by acecilia** [comment]
I have searched through the examples and the documentation but could not find anything related, can you explain me a bit more how to set menuView to navigationItem.titleView?

Right now I am using the controller with a storyboard, inside a containerView:  


    let pagingMenuController = self.childViewControllers.first as! PagingMenuController

    let options = PagingMenuOptions()
    options.menuHeight = 44
    options.backgroundColor = UIColor.mainGreenWTAColor
    options.selectedBackgroundColor = options.backgroundColor
    options.selectedTextColor = UIColor.whiteColor()
    options.font = UIFont(name: "Montserrat-Regular", size: 13)!
    options.selectedFont = options.font
    options.menuDisplayMode = .SegmentedControl
    options.menuItemMode = .Underline(height: 0.5, color: UIColor.grayColor(), horizontalPadding: 0, verticalPadding: 0)

    pagingMenuController.setup(viewControllers, options: options)


Do you mean something like this? (I run it but the menu is not being presented):

    let pagingMenuController = self.childViewControllers.first as! PagingMenuController

    let options = PagingMenuOptions()
    options.menuHeight = 44
    options.backgroundColor = UIColor.mainGreenWTAColor
    options.selectedBackgroundColor = options.backgroundColor
    options.selectedTextColor = UIColor.whiteColor()
    options.font = UIFont(name: "Montserrat-Regular", size: 13)!
    options.selectedFont = options.font
    options.menuDisplayMode = .SegmentedControl
    options.menuItemMode = .Underline(height: 0.5, color: UIColor.grayColor(), horizontalPadding: 0, verticalPadding: 0)

    pagingMenuController.setup(viewControllers, options: options)

    navigationItem.titleView = pagingMenuController.menuView

Thank you very much!

**Comment by acecilia** [comment]
My goal is very similar to the issue [117](https://github.com/kitasuke/PagingMenuController/issues/117)

**Comment by kitasuke** [comment]
If you call `setup` method again with new options which has new height, it's changed.

```
options.menuHeight = 30 // new height
pagingMenuController.setup(viewControllers, options: options)
```

**Comment by acecilia** [comment]
Nice, thanks it works perfectly! But when setting the height in iOS8.1 simulator this is happening: https://github.com/kitasuke/PagingMenuController/issues/230

Thank you very much
