### ISSUE TITLE
ViewWillApper() of selected view controller is not calling properly.

### ISSUE THREAD

**Issue by htarwara6245** [kitasuke/PagingMenuController#227]
Please add these code in PagingMenuControllerDemo2 in each controller

```
override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        print("VC 1")
}
```

You will see that ViewWillAppear is not called.

Another bug is the same on PagingMenuControllerDemo1.It called viewWillAppear().But,show me different view controller name.See the screenshot.

![paging error](https://cloud.githubusercontent.com/assets/10526402/15813602/5a035378-2be6-11e6-91f2-753a27f3b9e5.gif)

This bug is urgent to fix because to those who are working with UITableView resizable at iOS 8,they need to call 

```
 tableView.estimatedRowHeight = 100
 tableView.rowHeight = UITableViewAutomaticDimension
```

```
override func viewWillAppear(animated: Bool) {
        tableView.reloadData()
    }

```

which was one the bug of resizing tableview problem at iOS 8.So,if we cant call this method using your paging menu controller,it will not resize when view appear.

Any Help Please?

**Comment by kitasuke** [comment]
I'll investigate and fix this issue as soon as possible.

**Comment by htarwara6245** [comment]
Any help with that?I have waited for this answer.Becuase I implemented this in my large scale project.

**Comment by htarwara6245** [comment]
Issue still not fixed yet?I wonder what's taking you so long.Please help.Please fix this quick.

Thanks.

**Comment by kitasuke** [comment]
This is my side project. I don't guarantee quick fixes all the time. If you have some issues, your pull request is welcomed.

Why don't you use delegate methods instead?

```
func willMoveToPageMenuController(menuController: UIViewController, previousMenuController: UIViewController) {
}

func didMoveToPageMenuController(menuController: UIViewController, previousMenuController: UIViewController) {
}
```

**Comment by kitasuke** [comment]
Please use delegate methods above instead for now. I'll let you know when it's fully supported.

**Comment by htarwara6245** [comment]
It still not fixed yet.Why did you close this issue.And besides,I am still waiting for your fixes.

Here is my app and its on the App Store  : https://itunes.apple.com/us/app/telenor-myanmar-self-care-app/id952597596?mt=8 

which use your library for Internet Packages.

**Comment by kitasuke** [comment]
This library couldn't support calling `viewWillAppear` in child view controller at this moment. Please use delegate methods instead. `willMoveToPageMenuController` is equal to `viewWillAppear`, so I believe that there is no big difference for now.

**Comment by kitasuke** [comment]
It's some restrictions caused by this library's view mechanism. If it really matters to your project, I strongly recommend to use other similar library to solve it.
