### ISSUE TITLE
Using this library in obj-c project issue

### ISSUE THREAD

**Issue by sstepanovvl** [kitasuke/PagingMenuController#228]
First of all thank you for this great library, mr )
In my objective-c projects i used to use PageMenu library for userfriendly navigation, but i've noticed infinite menuScrollView and centered selected menu item looks much pretty than default PageMenu does.

And when i found PagingMenuController i tried to import this swift library into obj-c project. Everything seems to be fine, header files been created correctly, access to PagingMeniController class methods were granted.

But when i try to init PagingMenuController class with array of viewcontrollers with code:

```
#import "moyoutlet-Swift.h"

UIViewController* vc = [[UIViewController alloc] init];
vc.view.backgroundColor = [UIColor redColor];
vc.menuItemDescription = @"vc";

UIViewController* vc1 = [[UIViewController alloc] init];
vc1.view.backgroundColor = [UIColor whiteColor];
vc1.menuItemDescription = @"vc1";

NSArray* arr = [NSArray arrayWithObjects:vc,vc1, nil];

PagingMenuController* pvc = [[PagingMenuController alloc] initWithViewControllers:arr];

[self.view addSubview:pvc.view];
```

xcode through an error in method of MenuItemView.swift

`calculateLabelSize(label: UILabel, windowSize: CGSize = UIApplication.sharedApplication().keyWindow!.bounds.size) `

> fatal error: unexpectedly found nil while unwrapping an Optional value

and it seems that UIApplication.sharedApplication().keyWindow!.bounds.size returns nil.

Can u help me with that stuff? Is there correct way to use your library in obj-c project? Thanks once again!

**Comment by kitasuke** [comment]
This library officially doesn't support ObjC usage, but let me look into detail about this issue.

**Comment by sstepanovvl** [comment]
What can i do to speed up the solution to this issue?

**Comment by kitasuke** [comment]
Can you modify that code like below and run your project again?

```
calculateLabelSize(label: UILabel, windowSize: CGSize = 375)
```

**Comment by sstepanovvl** [comment]
> Default argument value of type 'int' cannot be converted t type 'CGSize'

but when i use 

`calculateLabelSize(label: UILabel, windowSize: CGSize = CGSizeMake(375, 667) `

windowsSize: {375, 667}
return {81, 19}

[Objective-c project for tests](https://github.com/sstepanovvl/PagingMenuControllerTest)

**Comment by sstepanovvl** [comment]
@kitasuke seems there is no success in this issue?

**Comment by kitasuke** [comment]
Thanks for providing sample project.
I haven't tried out yet, so please wait a moment.

**Comment by acecilia** [comment]
@sstepanovvl It is happening the same to me in swift, check [this](http://stackoverflow.com/questions/31324660/how-to-properly-handle-a-nil-uiapplication-sharedapplication-keywindow), I am quiet sure that it will help you. (My scenario was the one described in Situation 2)

**Comment by sstepanovvl** [comment]
@acecilia thanks! Placing init lines in viewdidappear solved problem with nil window, but there is another problem. while swiping between views  menuitem selection not working correctly... basically menuitem have no tap gesture recognizers... does project i've provided in previous message works fine ?
