### ISSUE TITLE
Navigation bar issue

### ISSUE THREAD

**Issue by tomhoffen** [kitasuke/PagingMenuController#229]
Hi, 

Im trying to customize the navigation bar for each view controller, but when I try to access it from each of the view controllers it is nil.

Is there something I miss?

Thanks

**Comment by kitasuke** [comment]
Can you share some source code about PagingMenuController usage?

**Comment by tomhoffen** [comment]
For instance if I have 2 ViewControllers in my PagingMenuController (for example Students and Teachers), 
So I want customize the navigation bar for differently for each one of them.

For instance in my StudentsViewController class, the viewWillAppear method looks as follows:

    override func viewWillAppear(animated: Bool) {
        let nav = self.navigationController
    }

nav is nil and not pointing to any object.

**Comment by kitasuke** [comment]
Does your parent view controller have navigation bar?
Anyway, I close this issue since it's not related to PagingMenuController.

**Comment by dhafinmuktafin** [comment]
Hi @tomhoffen, Have you found answer to your question? I also want to create it. I'm new to Swift programming. Thanks.

**Comment by tomhoffen** [comment]
Hi @dhafinmuktafin, 
I had to access parent?.parent?.parent?.navigationItem.
i.e: parent?.parent?.parent?.navigationItem.titleView = menuView

Hope it helps,
Tom

**Comment by dhafinmuktafin** [comment]
@tomhoffen Thanks for your reply. But I'm completely new to Swift programming. If you don't mind, would you please provide some details? 
Thanks in advance.
