### ISSUE TITLE
Version 1.0.0 PagingMenuOptions() deprecated!

### ISSUE THREAD

**Issue by Zfr21** [kitasuke/PagingMenuController#238]
gettin "Use of unresolved identifier 'PagingMenuOptions' " error after I updated to 1.0.0

let options = PagingMenuOptions()
options.menuDisplayMode = PagingMenuOptions.MenuDisplayMode.SegmentedControl
options.menuItemMode = PagingMenuOptions.MenuItemMode.None

**Comment by kitasuke** [comment]
Please take a look at README.md.

**Comment by Zfr21** [comment]
I took a look and implement whole necessary stuff(by looking demo example + readme.md), but I'm gettin  "fatal error: unexpectedly found nil while unwrapping an Optional value"

steps that I implement:

1) added PagingMenuControllerOptions.swift
2) added to each menu class -> class func instantiateFromStoryboard() -> AboutCityVC {
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    return storyboard.instantiateViewControllerWithIdentifier(String(self)) as! AboutCityVC
  }
3)added var options: PagingMenuControllerCustomizable! and 

    let pagingMenuController = self.childViewControllers.first as! PagingMenuController
    pagingMenuController.delegate = self

to holder class like in ur example

**Comment by kitasuke** [comment]
Example project would be helpful as well.

**Comment by Zfr21** [comment]
Thanks it solved my all problems :)
12 Haz 2016 19:50 tarihinde "Yusuke Kita" <notifications@github.com> yazdı:

**Comment by omidkh68** [comment]
@Zfr21 how did you solved problem??
I can't detect how to solve PagingMenuOptions() error in my code

**Comment by kitasuke** [comment]
@omidkh68  Did you notice that `PagingMenuOptions` class doesn't exist anymore? You can define `PagingMenuOptions` conforming `PagingMenuCustomizable` protocol as struct and pass it to `setup` method.

**Comment by omidkh68** [comment]
@kitasuke can You explain more clearly man?
#260
