### ISSUE TITLE
the example project doesn't work

### ISSUE THREAD

**Issue by arden** [kitasuke/PagingMenuController#240]
why the demo project doesn't work?

**Comment by kitasuke** [comment]
Can you share error message in console?

**Comment by arden** [comment]
Use of undeclared type 'MenuViewMode' in PagingMenuControllerOptions.swift.

**Comment by kitasuke** [comment]
Oh I forgot to update it...
I'll fix it tonight.

**Comment by kitasuke** [comment]
It's fixed with 1.1.1. Please try it out.
