### ISSUE TITLE
when use code to init PagingMenuController, the delegate won't be processed.

### ISSUE THREAD

**Issue by Guoxweii** [kitasuke/PagingMenuController#250]
when use code to init PagingMenuController

 ```
let pagingMenuController = PagingMenuController(options: options)
pagingMenuController.delegate = self
```

 the delegate won't be passed to MenuView's viewDelegate, so can you add a didset for delegate?

**Comment by kitasuke** [comment]
it's fixed in the latest version. Please try it out!
