### ISSUE TITLE
Use of unresolved identifier 'PagingMenuOptions' in swift project

### ISSUE THREAD

**Issue by EnVacance** [kitasuke/PagingMenuController#258]
Xcode Version 7.3
PagingMenu Version 1.1.2
I used cocoa pod to install the library.

Am I missing something?

Podfile

    source` 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!

    pod "PagingMenuController"`

ViewController

    import UIKit
    import PagingMenuController

    class ViewController: UIViewController {
    
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        
        let viewController1 = UIViewController()
        let viewController2 = UIViewController()
        let viewController3 = UIViewController()
        
        viewController1.view.backgroundColor = UIColor.redColor()
        viewController2.view.backgroundColor = UIColor.greenColor()
        viewController3.view.backgroundColor = UIColor.blueColor()
        
        viewController1.title = "VC1"
        viewController2.title = "VC2"
        viewController3.title = "VC3"
        let viewControllers = [viewController1, viewController2, viewController3]
        
        let options = PagingMenuOptions() // ***** Compile Error *****
        options.menuHeight = 60
        options.menuDisplayMode = .Infinite(widthMode: .Flexible, scrollingMode: .ScrollEnabled)
        
        let pagingMenuController = PagingMenuController(viewControllers: viewControllers, options: options)
        
        addChildViewController(pagingMenuController)
        view.addSubview(pagingMenuController.view)
        pagingMenuController.didMoveToParentViewController(self)
    }
    
    }

**Comment by adougies** [comment]
Same issue. Are you running Swift 3?

**Comment by EnVacance** [comment]
NO, I user Swift 2.2

**Comment by EnVacance** [comment]
I solved the problem by just using older version of the PagingMenu

**Comment by kitasuke** [comment]
There are some breaking changes with version 1.0.0+. Please take a look at README about how to use the library. PagingMenuOptions must conform 'PagingMenuControllerCustomizable' protocol.

See more detail here
https://github.com/kitasuke/PagingMenuController#usage
