### ISSUE TITLE
Keeping all loaded pages in memory

### ISSUE THREAD

**Issue by Shivam101** [kitasuke/PagingMenuController#259]
Hello,
I am using PagingMenuController with 4 different view controllers as pages. The current implementation keeps only 3 of them in memory at any point of time. (Current one and one on each side). How do I make sure that all 4 of them are available in memory at all times? 

My use case involves making a network call in one the pages and awaiting it's completion to load the UI. Before it completes, if I move >2 pages away from it, the UI is never loaded on the original pace. How can I allow the page to load in the background, no matter how many pages away from it I am. 

Thanks!

**Comment by weelh** [comment]
u can save the network data if move page before it success complete. And reload the page on actully viewWillAppear. See  网易新闻 client.

Never try to make all page in memory,is insignality to use this library.

**Comment by kitasuke** [comment]
I'm working on this.

**Comment by kitasuke** [comment]
It's supported in master branch.
