### ISSUE TITLE
tabs are not show in pagingMenuController

### ISSUE THREAD

**Issue by omidkh68** [kitasuke/PagingMenuController#260]
I'm so confused in PagingMenuControllerDemo!
Why my tabs not show in pagingMenuController?

where can I define my custom uiviewcontroller to show in each tab?
I set current in PagingMenuControllerOptions file but not work and tabs are not show!
code:
private var pagingControllers: [UIViewController] {
    let informationPage = InformationPage.instantiateFromStoryboard()
    let netbandMapDetailViewController = NetbandMapDetailViewController.instantiateFromStoryboard()
    return [informationPage, netbandMapDetailViewController]
}

your sample in PagingMenuControllerDemo was so that options set with segue in custom view controller but I don't understand how can I set options in pagingMenuController not even set with table cell.

Please Help me :(

**Comment by omidkh68** [comment]
@kitasuke :
I used this struct:
private struct PagingMenuOptions: PagingMenuControllerCustomizable {
    private var componentType: ComponentType {
        return .All(menuOptions: MenuOptions(), pagingControllers: pagingControllers)
    }
    
    private var pagingControllers: [UIViewController] {
        let informationPage = InformationPage.instantiateFromStoryboard()
        let netbandMapDetailViewController = NetbandMapDetailViewController.instantiateFromStoryboard()
        return [informationPage, netbandMapDetailViewController]
    }
    
    private struct MenuOptions: MenuViewCustomizable {
        var displayMode: MenuDisplayMode {
            return .SegmentedControl
        }
        var itemsOptions: [MenuItemViewCustomizable] {
            return [MenuItem1(), MenuItem2()]
        }
    }
    
    private struct MenuItem1: MenuItemViewCustomizable {
        var displayMode: MenuItemDisplayMode {
            return .Text(title: MenuItemText(text: "First Menu"))
        }
    }
    private struct MenuItem2: MenuItemViewCustomizable {
        var displayMode: MenuItemDisplayMode {
            return .Text(title: MenuItemText(text: "Second Menu"))
        }
    }
}

and this code in PagingMenuViewController viewDidLoad:
let options = PagingMenuOptions()
        
        let pagingMenuController = self.childViewControllers.first as! PagingMenuController
        pagingMenuController.delegate = self
        pagingMenuController.setup(options)
        
        pagingMenuController.view.frame.origin.y += 64
        pagingMenuController.view.frame.size.height -= 64
        
        addChildViewController(pagingMenuController)
        view.addSubview(pagingMenuController.view)
        pagingMenuController.didMoveToParentViewController(self)

but tabs not show!

**Comment by kitasuke** [comment]
Can you show the tabs with example project?

**Comment by SiNBizkit** [comment]
I'm not sure but I think the view don't change it origin position.
Do you try to move it under a UINavigationBar? If so as an experiment just try to set isTransluscent property of UINavigationBar to false:
`navigationController?.navigationBar.isTranslucent = false`

**Comment by kitasuke** [comment]
I think what @SiNBizkit suggested is a good way. Can you try that at first?
