### ISSUE TITLE
How can i change the text color of the Paging Menu and also the color of the line/bar of the menu when active/focused.

### ISSUE THREAD

**Issue by korantengNanaYaw** [kitasuke/PagingMenuController#262]
i am new to swift and iOS development,how can i change the text color of the Paging Menu and also the color of the line/bar of the menu when active/focused.

**Comment by kitasuke** [comment]
Use MenuItemText below.
https://github.com/kitasuke/PagingMenuController/blob/master/Pod/Classes/Protocols/MenuItemViewCustomizable.swift#L33:L50

```
let text = MenuItemText(text: String = "Menu",
                color: UIColor = UIColor.lightGrayColor(),
                selectedColor: UIColor = UIColor.blackColor(),
                font: UIFont = UIFont.systemFontOfSize(16),
                selectedFont: UIFont = UIFont.systemFontOfSize(16))
```

**Comment by korantengNanaYaw** [comment]
Thank you very much .

**Comment by kitasuke** [comment]
Please reopen this issue if you have further questions!

**Comment by korantengNanaYaw** [comment]
ok,sure will.

**Comment by adougies** [comment]
This should be in the readme
