### ISSUE TITLE
Nested swipeable content in tab

### ISSUE THREAD

**Issue by Shivam101** [kitasuke/PagingMenuController#263]
Hello,

I have implemented PagingMenuController with swiping enabled to traverse between tabs. 
Now, one of my tabs consists of a table view, which is editable, i.e. I can swipe at the cells to delete them etc. 
This doesn't work well with PagingMenuController's swiping as there is perhaps a conflict between the two actions. It works fine when the PMC's swipe is disabled however.

How can I achieve the above use case, whilst keeping both the tabs and the table view cells swipeable?

Would it be a viable option to set options.scrollEnabled to false when on this tab and enable it otherwise? How can this be achieved ?

Thanks!

**Comment by chlebta** [comment]
Hello,
you have to set `ScrollEnabled` option to false 
```
            let options = PagingMenuOptions()
            options.scrollEnabled = false 
 ...
```

**Comment by Shivam101** [comment]
Hello,

I have tried doing this, but this disables swipe entirely. I would like swipe to be usable, along with a nested swipe action on table view cells as well. I have thought of disabling swipe solely on the tab with the table view and enabling it elsewhere, but I am not sure of how to achieve this. 

Any thoughts on this?

Thanks!

**Comment by kitasuke** [comment]
I have no idea for that use case yet. It's technically difficult to detect you are swiping to edit your table view cell or move to other menu page.
It's a common issue when you use UIScrollView in UIScrollView, but I couldn't find the answer.

**Comment by kitasuke** [comment]
It's technically not because of this library, it's more like an issue of UIKit itself. I close this issue since there is no appropriate way for the case.
