### ISSUE TITLE
PagingMenuController.bundle: No such file or directory

### ISSUE THREAD

**Issue by pratik6554** [kitasuke/PagingMenuController#266]
For pod install i am getting following error

**/Build/Products/StageDebug-iphonesimulator## _/PagingMenuController/PagingMenuController.bundle_: No such file or directory**

Pod version : cocoapods-1.0.0.beta.6 

<img width="399" alt="screen shot 2016-08-30 at 12 54 54 pm" src="https://cloud.githubusercontent.com/assets/1791675/18079931/d21cccce-6eb0-11e6-9225-2eb3e043cb86.png">

the actual file path is /Products/StageDebug-iphonesimulator## _/PagingMenuController/PagingMenuController/PagingMenuController.bundle_

**Comment by kitasuke** [comment]
Can you upgrade your Cocoapods version and try it again?

**Comment by kitasuke** [comment]
Please reopen this issue if you still see with newer version of Cocoapods.

**Comment by pratik6554** [comment]
ok will check. Thanks.

**Comment by pratik6554** [comment]
@kitasuke Thank you, fixed with newer version of Cocoapods .
