### ISSUE TITLE
"Struct declaration cannot close over value 'self' defined in outer scope" and multiple instantiation of View Controllers in PMC

### ISSUE THREAD

**Issue by nickdnk** [kitasuke/PagingMenuController#270]
According to the documentation, the following code will implement the framework using storyboards.

```
struct MenuItem1: MenuItemViewCustomizable {}
struct MenuItem2: MenuItemViewCustomizable {}

struct MenuOptions: MenuViewCustomizable {
    var itemsOptions: [MenuItemViewCustomizable] {
        return [MenuItem1(), MenuItem2()]
    }
}

struct PagingMenuOptions: PagingMenuControllerCustomizable {
    var componentType: ComponentType {
        return .All(menuOptions: MenuOptions(), pagingControllers: [UIViewController(), UIViewController()])
    }
}

let pagingMenuController = self.childViewControllers.first as! PagingMenuController
pagingMenuController.delegate = self
pagingMenuController.setup(options)
```

Where do you define the `options` variable passed at the bottom? How do you customize it?

Also I cannot replace
`return .All(menuOptions: MenuOptions(), pagingControllers: [UIViewController(), UIViewController()])`

with

`return .All(menuOptions: MenuOptions(), pagingControllers: [myViewController1, myViewController2])` - it says:

`Struct declaration cannot close over value 'self' defined in outer scope.`

I don't understand where things get instantiated. It looked through the example project multiple times, but I cannot figure out which parts are essential and which parts are part of the demo only.

Can you please elaborate on how to as simply as possible send 2 view controllers to the PagingMenuController. I accomplished this with the beta version before it was converted to protocol oriented programming.

**Comment by nickdnk** [comment]
Okay - I made some progress, but I've come across something odd.

I pieced together some code from the examples and ended up with something that actually works, but I have some weird issues with a `UITableView` that insists on being white, but I don't think it has anything to do with PMC. It might just be iOS 10.

Anyway.

I use Storyboards to create a container view where I add the PMC class. I instantiate it like this:

```
override public func viewDidLoad() {
        super.viewDidLoad()
        
        options = PagingMenuOptions();
        
        pageControllerInstance = self.childViewControllers.first as! PagingMenuController
        pageControllerInstance.delegate = self
        pageControllerInstance.setup(options)
        
    }
```

Where `PagingMenuOptions()` is defined as such:

```
struct PagingMenuOptions: PagingMenuControllerCustomizable {
    
    var scrollEnabled: Bool {
        return false;
    }
    var componentType: ComponentType {
        return .All(menuOptions: MenuOptions(), pagingControllers: pagingControllers)
    }
    
    struct MenuOptions: MenuViewCustomizable {
        var displayMode: MenuDisplayMode {
            return MenuDisplayMode.SegmentedControl
        }
        var height: CGFloat {
            return 40
        }
        var itemsOptions: [MenuItemViewCustomizable] {
            return [MenuItemList(), MenuItemGraphic()]
        }
        var backgroundColor: UIColor {
            return UIColor.blackColor()
        }
        var selectedBackgroundColor: UIColor {
            return UIColor.blackColor()
        }
        var focusMode: MenuFocusMode {
            return .Underline(height: 3, color: UIColor .greenColor(), horizontalPadding: 0, verticalPadding: 0)
        }
    }
    
    struct MenuItemList: MenuItemViewCustomizable {
        var displayMode: MenuItemDisplayMode {
            return .Text(title: MenuItemText(text: "LIST VIEW", color: UIColor .lightGrayColor(), selectedColor: UIColor.lightGrayColor(), font: UIFont.systemFontOfSize(11), selectedFont: UIFont.systemFontOfSize(12)));
        }
    }
    
    struct MenuItemGraphic: MenuItemViewCustomizable {
        var displayMode: MenuItemDisplayMode {
            return .Text(title: MenuItemText(text: "GRAPHIC VIEW", color: UIColor .lightGrayColor(), selectedColor: UIColor.lightGrayColor(), font: UIFont.systemFontOfSize(11), selectedFont: UIFont.systemFontOfSize(12)));
        }
    }
}
```

Which uses the private var that looks like this:

```
private var pagingControllers: [UIViewController] {
    
    let storyboard = UIStoryboard(name: "Main", bundle: nil)

 // I have a lot of code here that set ups my view controllers from the storyboard and returns them below.
    
    print("TEST");
    
    return [tableView1, tableView2]
    
}
```

TEST is printed to the console many, many times when the app switches between View Controllers using PMC. That can't be right? Why would you need to reinstantiate all of the ViewControllers 8-9 times in a row?

**Comment by PhilizSwiss** [comment]
I've the same problem... How can I access in PagingMenuOptions to viewControllers defined outside the struct ?

**Comment by kitasuke** [comment]
Thanks for reporting this. I'll fix it.

**Comment by PhilizSwiss** [comment]
Thanks, any idea when it could be fixed? I'm blocked on this.

**Comment by PhilizSwiss** [comment]
I found a way to do this. Just by adding a init(xxx) function to the struct and passing whatever we want to that function.

**Comment by nickdnk** [comment]
Does that also solve the problem with constant reinstantiation when going back and forth between VCs?


On 17 Oct 2016, at 11.21, PhilizSwiss <notifications@github.com<mailto:notifications@github.com>> wrote:


I found a way to do this. Just by adding a init(xxx) function to the struct and passing whatever we want to that function.

-

**Comment by kitasuke** [comment]
Can you move setup code outside of `fileprivate var pagingControllers: [UIViewController] {}` like below? Because this property is simply getter.
There might be a better way, so I'll think about another solution for this anyway.

```
    lazy var viewController: UIViewController = {
        $0.view.backgroundColor = UIColor.blue
        ... // do something
    }(UIViewController())

    fileprivate var pagingControllers: [UIViewController] {
        return [viewController]
    }
```

**Comment by nickdnk** [comment]
Hello

This is still a big problem. I cannot upgrade to latest version because I still cannot access the view controllers from outside PagingMenuOptions() struct. I don't know what you mean.

I have my view controllers as instance variables in my root view controller. These are instantiated from the storyboard using self.storyboard. I cannot do this now.

Previously I could do:

`pageControllerInstance.setup([myViewController1,myViewController2], options: options)`

From my root view controller. This was fine.

**Comment by kitasuke** [comment]
First of all, it's nothing to do with latest version.
Second of all, I can not advise anything without your code. Can you share your all of codes related to this library?

**Comment by nickdnk** [comment]
I was referring to "There might be a better way, so I'll think about another solution for this anyway." - as in, the latest version still does not address the problem.

My instantiation looks like this, in my root view controller.

I need viewControllerList and viewControllerGraphic as instance variables in this class, so whenever I upgrade to PMC 2.x I end up with the struct scope problem where I cannot access the view controllers. I don't know how to get around that :(

```
viewControllerList = self.storyboard?.instantiateViewControllerWithIdentifier("tables_list") as! TableOverviewTableViewController;
viewControllerList.title = "LIST VIEW";
        
viewControllerGraphic = self.storyboard?.instantiateViewControllerWithIdentifier("tables_graphic") as! GraphicTablePageTableViewController
viewControllerGraphic.title = "GRAPHIC VIEW";
        
pageControllerInstance = self.childViewControllers.first as! PagingMenuController
        
pageControllerInstance.delegate = self;
        
let options = PagingMenuOptions()
options.menuHeight = 40;
options.menuItemMode = .Underline(height: 3, color: UIColor.greenColor(), horizontalPadding: 0, verticalPadding: 0)
        
options.selectedTextColor = UIColor.lightGrayColor()
options.textColor = UIColor.lightGrayColor()
options.font = UIFont.systemFontOfSize(11)
options.selectedFont = UIFont.systemFontOfSize(12)
options.selectedBackgroundColor = UIColor.blackColor()
options.backgroundColor = UIColor.blackColor()
options.scrollEnabled = false;
options.menuDisplayMode = .SegmentedControl;
pageControllerInstance.setup([viewControllerList,viewControllerGraphic], options: options)
```

**Comment by kitasuke** [comment]
Did you take a look at example project in version 2.x? You can see usage of this library.
https://github.com/kitasuke/PagingMenuController/blob/master/Example/PagingMenuControllerDemo/PagingMenuControllerOptions.swift

**Comment by nickdnk** [comment]
I did. But in that example you do not communicate with objects outside the scope of the `struct`  - I cannot use `self.storboard....` because I cannot access `self` within the `struct`.

Purely from an architectural standpoint, the View Controllers **do not** belong inside the `options` struct, as they are **not** an option of PMC. They are an external and _unknown_ dependency. You should modify it so the view controllers become a part of the constructor independently from `options`.

This is a bad idea:
````
options = PagingMenuOptions();  <--- View Controllers are inside here. Why? View Controllers are not a part of PMC code.

pageControllerInstance = self.childViewControllers.first as! PagingMenuController
pageControllerInstance.delegate = self
pageControllerInstance.setup(options)
````

It would be much better if the logic was:

````
options = PagingMenuOptions(); <--- This should contain ONLY PMC logic and setup, nothing external.

pageControllerInstance = self.childViewControllers.first as! PagingMenuController
pageControllerInstance.delegate = self
pageControllerInstance.setup(options, viewControllers) <-- Like this. An array injected into the constructor.
````

**Comment by kitasuke** [comment]
I see your point about dependency. What you are saying is that you just don't want to have any dependency with options right? You can access storyboard or whatever if you make a custom initializer for option and simply pass it, but it's not the option for you.
For that case, you can still use 0.x version, but it's not maintained anymore unfortunately.

**Comment by nickdnk** [comment]
Yes, I believe options should be PMC *options* only, and not view controllers. It reduces the flexibility of the project when VCs are scoped in with options.

Do you have a suggestion for a solution? The problem is that 0.10.x is Swift 2.3, and that will be deprecated. I am not experienced with Swift, so I don't know how to upgrade it. Will the automatic XCode converter work on it, do you think?

**Comment by nickdnk** [comment]
Hello again

I figured out what you mean. I did this to solve the problem:

```
/** I instantiate my viewControllers here (viewControllerList and viewControllerGraphic) **/

pageControllerInstance = self.childViewControllers.first as! PagingMenuController
pageControllerInstance.setup(PagingMenuOptions(viewControllerList : viewControllerList, viewControllerGraphic : viewControllerGraphic));
```

And then customized the PagingMenuOptions like:

```
private struct PagingMenuOptions: PagingMenuControllerCustomizable {
    
    var viewControllerList: TableOverviewTableViewController
    var viewControllerGraphic: GraphicTablePageTableViewController

    .... and so on.
}
```

It works!

But I noticed I cannot change the font color of the selectedItem for `MenuFocusMode.underline()`? I could do this in 0.10. I don't want to use `roundRect` :(  It automatically becomes black, and my background is black, so the font "disappears" when selected. How do I modify the font of `MenuItemViewCustomizable` ?

**Comment by shaikshabana** [comment]
Can any one help me to use the existing pod as i am getting struct cleared cannot close where i will pass array of viewcontrollers

        let options = PagingMenuOptions()
        options.menuItemMargin = 0
        options.menuHeight = 0
        options.menuDisplayMode = .SegmentedControl
        self.pagingMenuController = PagingMenuController(viewControllers: viewControllers, options: options)
        self.pagingMenuController!.view.frame.origin.y += 64
        self.pagingMenuController!.view.frame.size.height -= 85 + 64
        addChildViewController(self.pagingMenuController!)
        view.addSubview(self.pagingMenuController!.view)
        self.pagingMenuController?.delegate = self
        self.pagingMenuController!.didMove(toParentViewController: self)
        self.pagingMenuController?.moveToMenuPage((self.selectedIndexPath), animated: true)

Please help me to replace this code with swift 3 as i am unable to add viewControllers[self] in struct.

**Comment by kitasuke** [comment]
Example project might be helpful because it's written in Swift 3.
