### ISSUE TITLE
please support swift3.0 thanks

### ISSUE THREAD

**Issue by Mosaics** [kitasuke/PagingMenuController#271]

**Comment by kitasuke** [comment]
Please watch this PR #243 , it'll be merged soon.

**Comment by hamzauzumcu** [comment]
When will be published the update

**Comment by kitasuke** [comment]
I'll merge this PR, Once I solve an issue with CocoaPods.

**Comment by RTimal** [comment]
yes, Please! :)

**Comment by kitasuke** [comment]
Please use 1.3.1 version. There are a few changes for Swift 3, so take a look at READ.md.
