### ISSUE TITLE
How to dynamic change selectedBackgroundColor?

### ISSUE THREAD

**Issue by Amefuri** [kitasuke/PagingMenuController#279]
Is there's a way to dynamically change selectedBackgroundColor of MenuOptions: MenuViewCustomizable depend on which menuOption that currently selected?

Thank you,

**Comment by quiKsilverItaly** [comment]
I insert dynamically the title and background color in my PagingMenuController. 
The idea is to create structs for yourself, which inherit from `MenuViewCustomizable` and so on, and inserting the information into the `init` method. Then you can use the Structs in your project.

Here is my code: http://pastebin.com/Rifu5eTE

**Comment by Amefuri** [comment]
Awe Thank you a lot @quiKsilverItaly 
will try out your solution now
