### ISSUE TITLE
I cant assign options in my PagingMenuOptions

### ISSUE THREAD

**Issue by GusSerra** [kitasuke/PagingMenuController#28]

**Comment by kitasuke** [comment]
If you want other options, please tell me what you want. So I'll implement it.

**Comment by GusSerra** [comment]
![error](https://cloud.githubusercontent.com/assets/1130111/8510095/634bf0c4-22a6-11e5-9319-d74593b515fd.jpg)

**Comment by kitasuke** [comment]
That was critical bug and fixed a while ago. Please use version 0.4.1.
Thank you for your report!
