### ISSUE TITLE
Delegate-Methods don't work anymore at version 2.0

### ISSUE THREAD

**Issue by quiKsilverItaly** [kitasuke/PagingMenuController#280]
So I updated my project to Swift 3 and also updated PagingMenuController to its newest version 2.0.0. Deployment target is iOS9.
The problem is, that the Delegate-Methods in my Controller don't get called anymore. I will provide an example: 

1) The user makes an interaction.
2) Inside the library everything seems to work fine, also the delegate-methods get called. See: http://www2.pic-upload.de/img/31794431/page1.jpg
3) But the methods here in my controller never get called. See: http://www2.pic-upload.de/img/31794430/page2.jpg Before migrating to Swift 3 and updating the lib this worked flawlessly.

I already recognized, that the Delegate-Methods got renamed, and corrected this properly. Of course I am using `pagingMenuController.delegate = self` and `PagingMenuControllerDelegate`. 

What's the problem here?

**Comment by quiKsilverItaly** [comment]
Found the problem. Had nothing to do with the Lib itself, but some weird change in Swift3. 
I set the `delegate = self` in my super class, but implement the delegate method in the child classes. This doesn't work anymore. The delegate method must be also implemented in the super class. 

You can close this. Thanks for the great lib by the way.

**Comment by kitasuke** [comment]
Sorry, I wasn't able to make unavailable method with @available attribute. I'm still trying giving some instruction for this. I'll update once its done.
