### ISSUE TITLE
Impossible to wire the menuView.viewDelegate

### ISSUE THREAD

**Issue by simoami** [kitasuke/PagingMenuController#281]
Hello,
I'm using the menu mode from PagingMenuController (componentType = .MenuView)

Despite setting the delegate, I'm not getting delegate methods called. Debugging shows that the menuView.viewDelegate being assigned at controller instantiation time, before assigning a delegate:

```
let options = PagingMenuOptions()
pagingMenuController = PagingMenuController(options: options) <-- viewDelegate assignment happens here via constructMenuView() -> menuView didSet {}
pagingMenuController!.delegate = self <-- too late for the delegate to attach to the menuView
```

I'm using v1.2.0 for Swift 2.3 xcode 8.

**Comment by kitasuke** [comment]
Thanks for reporting this issue. It was a bug and fixed in master branch.
