### ISSUE TITLE
Parse data to the first child page

### ISSUE THREAD

**Issue by SwordElucidator** [kitasuke/PagingMenuController#294]
Hi, I am new to this and I wonder this would be an easy question. How should I parse data by segue to the first child page so that it will show the right information when loaded?

I read the previous issues and solved the data transitions on other pages by 
`willMove(toMenu menuController: UIViewController, fromMenu previousMenuController: UIViewController)`, but I could not find out how to deal with the first page on the first time loading.

Anyone like to help me with this? I appreciate it so much!

日本語でも大丈夫です。

**Comment by crazystudy** [comment]
I have a same problem with you , did you fix it?

**Comment by crazystudy** [comment]
@SwordElucidator  I have a same problem with you, did you fix it?

**Comment by SwordElucidator** [comment]
@crazystudy  Hey dude, sorry for waiting. I finally got it by adding an ```init``` function in **PagingMenuControllerCustomizable** class (which is the option that you'll use to set up **pagingMenuController** later.) to parse data when the page menu controller is generated.

```swift
struct PagingMenuOptions: PagingMenuControllerCustomizable {

    //get the children of paging menu controller
    let page1 = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "Controller1") as! Controller1
        
    let page2 = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "Controller2") as! Controller2

    fileprivate var pagingControllers: [UIViewController] {
        return [self.page1, self.page2]
    }

    init(var1: Type1, var2: Type2) {
        page1.var1 = var1
        page2.var2 = var2
        page2.doSomeFunction()
    }


}
```

Then when you initialize paging Menu Controller, parse your data from the parent view like this:
```
    let options = PagingMenuOptions(var1: var1, var2: var2)
    let pagingMenuController = PagingMenuController(options: options)
```

Then it should work! If you want to parse in data later, it's fine to call other functions to do it as I said in the question so BEST WISHES!

**P.S.**  For others who might need the answer I used English to write. 我讲中文，所以有什么问题的话可以问我~虽然我也是纯新手啦。

**Comment by SwordElucidator** [comment]
If nothing more to do with this issue, I think it's fine to close it. Thanks!

**Comment by crazystudy** [comment]
@SwordElucidator  方便的话加下Q 339120789 我看了你的答案 还有点疑惑想请教下

**Comment by crazystudy** [comment]
@SwordElucidator  谢谢,问题已经解决了.不过我想知道原因

**Comment by crazystudy** [comment]
@SwordElucidator  按你说的方法我试了,还是失败.能否加个Q,跟你详细请教下.

**Comment by SwordElucidator** [comment]
@crazystudy 不好意思前两天病了，可以啊。457639904，欢迎
