### ISSUE TITLE
BackgroundColor of ViewControllers

### ISSUE THREAD

**Issue by Niphery** [kitasuke/PagingMenuController#295]
- Expected behavior and actual behavior.
- Steps to reproduce the problem.

**If building the demo2, the two ViewController display should have a gray background.
However the background is plain white.**

**Also the delegate methods for the menuItem seems to have issues. For some reason they're not called. I'm working on it and will come back if I cant find why. Here a sample if you wish to have a look. It's mostly just a copy of the demo2 to play around the settings.**
- Specifications like the version of the project, library, or Swift.
**I'm currently using xcode 8.1 and swift 3**

**Comment by kitasuke** [comment]
It's fixed. Please use 2.1.0 version.
