### ISSUE TITLE
Invalid animation of MenuView with infinite mode

### ISSUE THREAD

**Issue by hiragram** [kitasuke/PagingMenuController#301]
Hi, @kitasuke 

I have been trying to PagingMenuController to our app, but I am facing a probrem with infinite mode.
I am using the latest release of PagingMenuController.

When I use infinite mode, dummy items are generated (the number is configured with `dummyItemViewSet` and default is 3).

It animates incorrectly when:

- user canceled swipe on `contentScrollView`
- current menu item was generated as dummy view

Screen capture is as follows:

![pager](https://cloud.githubusercontent.com/assets/3433324/20477752/75aceff4-b01a-11e6-8255-69b5d3097d9f.gif)

I have been trying to solve this issue by myself, but I could not find how I should fix this bug.

User(initial tab) -> Repository -> Gists -> Organization -> User(dummy)

then user canceled swipe, menu item goes back to User(initial tab).

- [x] Expected behavior and actual behavior.
- [x] Steps to reproduce the problem.
- [x] Specifications like the version of the project, library, or Swift.

**Comment by hiragram** [comment]
Are you going to fix this issue? @kitasuke

**Comment by kitasuke** [comment]
Yes, but it's still on todo list.

**Comment by kitasuke** [comment]
It's fixed. Please use 2.1.0 version.

**Comment by hiragram** [comment]
Thank you! 👍
