### ISSUE TITLE
50 : 50 width of menu

### ISSUE THREAD

**Issue by gunantosteven** [kitasuke/PagingMenuController#308]
Hi, I need a help.
I have two menu item and I want the size of width menu item equal. Take a look screenshoots below.

Expectation  

<a href="http://imgh.us/imgpsh_fullsize_(1).jpg" target="_blank"><img src="http://imgh.us/imgpsh_fullsize_(1).jpg" widht=300 height=300 /></a>

Actual

<a href="http://imgh.us/imgpsh_fullsize.png" target="_blank"><img src="http://imgh.us/imgpsh_fullsize.png" widht=300 height=300 /></a>

Do i need to use fixed size to do that ?

Any help thanks.

**Comment by kitasuke** [comment]
You can do like above with `segmentedControl`.

```
public enum MenuDisplayMode {
    case standard(widthMode: MenuItemWidthMode, centerItem: Bool, scrollingMode: MenuScrollingMode)
    case segmentedControl
    case infinite(widthMode: MenuItemWidthMode, scrollingMode: MenuScrollingMode) // Requires three paging views at least
}
```

**Comment by gunantosteven** [comment]
How about the underline ? It's still not appropriate

<a href="http://imgh.us/imgpsh_fullsize_(1).png" target="_blank"><img src="http://imgh.us/imgpsh_fullsize_(1).png" widht=300 height=300 /></a>

Thanks

**Comment by kitasuke** [comment]
What do you mean by not appropriate? Do you want to make it shorter?

**Comment by gunantosteven** [comment]
I want to make it longer.

**Comment by kitasuke** [comment]
You can change length of underline with these paddings.

```
focusMode: MenuFocusMode
public enum MenuFocusMode {
    case none
    case underline(height: CGFloat, color: UIColor, horizontalPadding: CGFloat, verticalPadding: CGFloat)
    case roundRect(radius: CGFloat, horizontalPadding: CGFloat, verticalPadding: CGFloat, selectedColor: UIColor)
}
```

**Comment by gunantosteven** [comment]
Can first underline and second underline size be different ?

Thanks

**Comment by kitasuke** [comment]
Unfortunately no...

**Comment by kitasuke** [comment]
Sorry to say, but this won't be supported for a while. So I close this issue.
I'll let you know if it's done.
