### ISSUE TITLE
How to configure menu bar of pagingMenuController

### ISSUE THREAD

**Issue by jon0003** [kitasuke/PagingMenuController#309]
Hi,
how can I create a menu bar (or navigationbar) that is above the the tap bar? In the examples I see that there is at least a title named "PagingMenuController". How can I code in this area?

I just use a UIViewController together with a xib file, to get the pagingMenuController working like:

override func viewDidLoad() {
        super.viewDidLoad()
        
        view.backgroundColor = Helper.hexStringToUIColor("#00887A")

        let options = PagingMenuOptions()
        let pagingMenuController = PagingMenuController(options: options)
        pagingMenuController.view.frame.origin.y += 64
        pagingMenuController.view.frame.size.height -= 64

        pagingMenuController.move(toPage: 1, animated: true) //.moveToMenuPage(1, animated:     false)

        
        pagingMenuController.view.width = view.width
        pagingMenuController.view.height = view.height
        
        addChildViewController(pagingMenuController)
        view.addSubview(pagingMenuController.view)
        pagingMenuController.didMove(toParentViewController: self)
}

**Comment by kitasuke** [comment]
`UIViewController` has a `title` property which is text on navigation bar, so you can simply set some text to the property like below.

```
class ViewControoler: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        title = "title"
    }
}
```
