### ISSUE TITLE
How to change color of underline 

### ISSUE THREAD

**Issue by mkaya93** [kitasuke/PagingMenuController#313]
Hi,

I just want to learn How can I change underline's color. 

I looked options but couldn't find anything about underline.

**Comment by kitasuke** [comment]
You can set your color here.

```
focusMode: MenuFocusMode
public enum MenuFocusMode {
    case none
    case underline(height: CGFloat, color: UIColor, horizontalPadding: CGFloat, verticalPadding: CGFloat)
    case roundRect(radius: CGFloat, horizontalPadding: CGFloat, verticalPadding: CGFloat, selectedColor: UIColor)
}
```

**Comment by JasonGreenAmerica** [comment]
no working... it being ignored.


fileprivate struct MenuOptions: MenuViewCustomizable {
        fileprivate var backgroundColor: UIColor{
            return UIColor(colorWithHexValue: 0x1F242C, alpha: 1)
        }
        fileprivate var selectedBackgroundColor: UIColor{
            return UIColor(colorWithHexValue: 0x1F242C, alpha: 1)
        }
        var focusMode: MenuFocusMode {
            return .roundRect(radius: 12, horizontalPadding: 8, verticalPadding: 8, selectedColor: UIColor.lightGray)
        }
        var displayMode: MenuDisplayMode {
            return .segmentedControl
        }
        var itemsOptions: [MenuItemViewCustomizable] {
            return [MenuItem1(), MenuItem2(), MenuItem3()]
        }
    }

**Comment by kitasuke** [comment]
You should use `underline` option for `MenuFocusMode`

**Comment by JasonGreenAmerica** [comment]
i changed to underline...it still seems to get ignored.

fileprivate struct MenuOptions: MenuViewCustomizable {
        fileprivate var backgroundColor: UIColor{
            return UIColor(colorWithHexValue: 0x1F242C, alpha: 1)
        }
        fileprivate var selectedBackgroundColor: UIColor{
            return UIColor(colorWithHexValue: 0x1F242C, alpha: 1)
        }
       var focusMode: MenuFocusMode {
            return .underline(height: 3, color: UIColor.red, horizontalPadding: 0, verticalPadding: 0)
        }
        var displayMode: MenuDisplayMode {
            return .segmentedControl
        }
        var itemsOptions: [MenuItemViewCustomizable] {
            return [MenuItem1(), MenuItem2(), MenuItem3()]
        }
    }

**Comment by kitasuke** [comment]
Can you take a look at example project? It works fine.

**Comment by kitasuke** [comment]
I'll close this issue since you create a new one. #327
