### ISSUE TITLE
tableviewlang.delegate in subViewController

### ISSUE THREAD

**Issue by MansoorJafari** [kitasuke/PagingMenuController#314]
Hi
In an one  subview I want use tableView , But in viewDidLoad() error 

tableviewlang.delegate = self
tableviewlang.dataSource = self

this error is

unexpectedly found nil while unwrapping an Optional value

for this line  tableviewlang.delegate = self
my subclass is 

`class GroupLangVC: UIViewController,UITableViewDataSource,UITableViewDelegate {
    

    @IBOutlet weak var tableviewlang: UITableView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableviewlang.dataSource = self
        tableviewlang.delegate = self
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 5
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cell = tableviewlang.dequeueReusableCell(withIdentifier: "celllanguege", for: indexPath) as? TableViewCellGroup {
            cell.ConfigureCell(gName: "M\(indexPath.row)")
            
            return cell
        }
        return TableViewCellGroup()
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 90.0
    }
    

}
`

please help. Thanks

**Comment by kitasuke** [comment]
Maybe you don't connect IBOutlet on your storyboard, but I can't say what's wrong there without more detailed info. On top of that, it looks like there is nothing to do with PagingMenuController, so I close this issue.

**Comment by MansoorJafari** [comment]
Thanks for your answer.

after I use this controller without PagingMenuController work fine. 

Is there a solution for set delegate in pagingmenu controller?

Thanks,

**Comment by kitasuke** [comment]
Again, there is nothing I can say at this moment without further sample codes since I couldn't see any code related to PagingMenuController.

**Comment by MansoorJafari** [comment]
Thanks.
my problem is solve.

**Comment by kitasuke** [comment]
Good to know.

**Comment by uknowmeright** [comment]
I am running into the same exact issue. What did you do to solve your problem?

thanks
