### ISSUE TITLE
Menu not showing when added programatically

### ISSUE THREAD

**Issue by kayvink** [kitasuke/PagingMenuController#32]
Yesterday I implemented the PagingMenuController by copying the storyboard and working from your example, this worked perfectly fine. I'd rather do it programatically though, but the menu is not showing up now. Is there something I am missing?

my `didFinishLaunchingWithOptions` looks somethings like this

```swift
self.window = UIWindow(frame: UIScreen.mainScreen().bounds)
let containerViewController = ContainerViewController()
let navigationContoller = UINavigationController(rootViewController: containerViewController)
self.window!.rootViewController = navigationContoller
self.window!.makeKeyAndVisible()
```

Then later I configure the menu the same way as in the readMe

```swift
let viewController = UIViewController()
viewController.title = "First title"

let viewController2 = UIViewController()
viewController2.title = "Second title"

let viewControllers = [viewController, viewController2]

let options = PagingMenuOptions()
options.menuItemMargin = 5
options.menuHeight = 60
options.menuDisplayMode = PagingMenuOptions.MenuDisplayMode.SegmentedControl
let pagingMenuController = PagingMenuController(viewControllers: viewControllers, options: options)

self.addChildViewController(pagingMenuController)
self.view.addSubview(pagingMenuController.view)
pagingMenuController.didMoveToParentViewController(self)
```

The menu bar doesn't show but I can transition between VC's. What am I doing wrong?

**Comment by kitasuke** [comment]
Well, I created a new project and copied the codes shown above. However it works fine for me.
Could you send me some screenshots?

**Comment by kitasuke** [comment]
I guess I got your point. I've just fixed it and updated to 0.4.2 version.
So please use 0.4.2 and if there is still a bug, comment here again.
For your information, I added `PagingMenuControllerDemo2` target implemented programmatically. Hope it would be helpful for you.

**Comment by kayvink** [comment]
Sorry for the late response, and thanks a lot will have a look right now.

**Comment by kitasuke** [comment]
:+1: 
Don't forget run `pod install` in terminal if you want to run example project.

**Comment by kayvink** [comment]
Thank works. Thanks 💪🏼

**Comment by kitasuke** [comment]
Awesome :smile:
