### ISSUE TITLE
standardモードでページ数が2の場合のPagingMenuViewの挙動に関して

### ISSUE THREAD

**Issue by minerva1129** [kitasuke/PagingMenuController#321]
はじめまして、日本人の方とお見受けしたため、恐縮ですが日本語で質問させてください。
standardモードでページ数が2の場合のPagingMenuViewの挙動に関してですが、添付のgifのように左右に動いてしまい、不自然に感じたのですが、これは意図された挙動でしょうか？
![paging_issue](https://cloud.githubusercontent.com/assets/7879128/21932145/600755c6-d9e2-11e6-84d8-6ffe1cac786c.gif)

**Comment by kitasuke** [comment]
そうです。standardモードは全タブの横幅が画面幅より大きい前提の作りです。この場合は代わりにsegmentedControlモードを使用してください。

**Comment by minerva1129** [comment]
了解しました ありがとうございました
