### ISSUE TITLE
How to add underline?

### ISSUE THREAD

**Issue by mengheangrat** [kitasuke/PagingMenuController#324]
<img width="474" alt="screen shot 2017-01-17 at 6 08 59 pm" src="https://cloud.githubusercontent.com/assets/10340553/22018167/1a407300-dce0-11e6-9c51-73214c4c143b.png">

**Comment by kitasuke** [comment]
Please use `underline` property.

```
public enum MenuFocusMode {
    case none
    case underline(height: CGFloat, color: UIColor, horizontalPadding: CGFloat, verticalPadding: CGFloat)
    case roundRect(radius: CGFloat, horizontalPadding: CGFloat, verticalPadding: CGFloat, selectedColor: UIColor)
}
```

**Comment by kitasuke** [comment]
Please reopen this issue if setting `underline` doesn't work.
