### ISSUE TITLE
fileprivate var focusMode: MenuFocusMode is ignored /swift 3/ 1OS 10.2

### ISSUE THREAD

**Issue by JasonGreenAmerica** [kitasuke/PagingMenuController#327]
fileprivate struct MenuOptions: MenuViewCustomizable {
        fileprivate var backgroundColor: UIColor{
            return UIColor(colorWithHexValue: 0x1F242C, alpha: 1)
        }
        fileprivate var selectedBackgroundColor: UIColor{
            return UIColor(colorWithHexValue: 0x1F242C, alpha: 1)
        }
        fileprivate var focusMode: MenuFocusMode{
             return .underline(height: 3, color: UIColor.red, horizontalPadding: 0, verticalPadding: 0)
        }
        var displayMode: MenuDisplayMode {
            return .segmentedControl
        }
        var itemsOptions: [MenuItemViewCustomizable] {
            return [MenuItem1(), MenuItem2(), MenuItem3()]
        }
    }
<img width="468" alt="screen shot 2017-01-29 at 9 55 11 am" src="https://cloud.githubusercontent.com/assets/13971059/22406496/0cd13e98-e609-11e6-93dc-675955221478.png">

**Comment by kitasuke** [comment]
Can you take a look at example project? It works fine.

**Comment by kitasuke** [comment]
The example project works on iOS 10.2 in Swift 3. Can you follow same way just like example project? Please reopen this issue if it still doesn't work.
