### ISSUE TITLE
Value of type 'PagingMenuController' has no member 'onMove'.

### ISSUE THREAD

**Issue by kishor010** [kitasuke/PagingMenuController#328]
@newbdez33 @wwwjfy 
    
              pagingMenuController.onMove = { state in
                 switch state {
            case let .willMoveController(menuController, previousMenuController):
                print(previousMenuController)
                print(menuController)
            case let .didMoveController(menuController, previousMenuController):
                print(previousMenuController)
                print(menuController)
            case let .willMoveItem(menuItemView, previousMenuItemView):
                print(previousMenuItemView)
                print(menuItemView)
            case let .didMoveItem(menuItemView, previousMenuItemView):
                print(previousMenuItemView)
                print(menuItemView)
            case .didScrollStart:
                print("Scroll start")
            case .didScrollEnd:
                print("Scroll end")
            }
        }

**Comment by wwwjfy** [comment]
@kishor010 I don't know why it's related to me, but I can see `onMove` is declared in `PagingMenuController` [here](https://github.com/kitasuke/PagingMenuController/blob/master/Pod/Classes/PagingMenuController.swift#L47)

**Comment by kitasuke** [comment]
It might work if you clear cache and reinstall via CocoaPods or Carthage

**Comment by kishor010** [comment]
OK let me check reinstall it.
Thanks @kitasuke

**Comment by kitasuke** [comment]
Please reopen if you still see the issue.

**Comment by richard-lifeco** [comment]
still seeing this issue

**Comment by richard-lifeco** [comment]
need to ensure that the minimum deployment value is set to 9 in the pod file
