### ISSUE TITLE
Positioning MenuView Subview

### ISSUE THREAD

**Issue by jangerhofer** [kitasuke/PagingMenuController#36]
Is there an easy way to move the MenuView to the bottom of the associated container view, instead of the top where it currently displays?  I've tried modifying the framework's vertical NSLayoutConstraint.constraintsWithVisualFormat for the layoutMenuView() function, but this resizes the entire container (I assume because the sizing of the container is based on the height of the menuContainer).  

It looks like I will need to rewrite all of the sizing logic in PagingMenuController -- am I mistaken?

**Comment by kitasuke** [comment]
Yes, need to modify the logic. I'll prepare a new option for the menu view position, top or bottom.

**Comment by kitasuke** [comment]
Just added the option to 0.4.3 version. Please use this one!
