### ISSUE TITLE
Animation for the selected tab

### ISSUE THREAD

**Issue by mingming1234** [kitasuke/PagingMenuController#44]
Would you mind to add the animation changing the position of underline of the selected tabs? For the Obj-C library uacaps/PageMenu, there is an option called scrollAnimationDurationOnMenuItemTap that can control it. I hope you can add this animation effect to the library. Thanks.

**Comment by kitasuke** [comment]
Alright, I'm working on it!

**Comment by kitasuke** [comment]
Please use version 0.4.5! Let me know if there is still something wrong.

**Comment by mingming1234** [comment]
It works. Thank you so much.

**Comment by kitasuke** [comment]
:smile:
