### ISSUE TITLE
Crash when menuItemViews.count == 1

### ISSUE THREAD

**Issue by kayvink** [kitasuke/PagingMenuController#48]
My app crashes if I run the `PagingMenuController` with only one viewController

I have tracked the bug down to `contentOffsetXForCurrentPage` in `MenuView`.

`menuItemViews.count` is 1
`nextIndex`  is 0
`menuItemViews.count - 1 ` is 0
`let ratio = nextIndex / menuItemViews.count - 1` is 0 / 0 which returns `nan`

Here is the error log:
`2015-07-27 13:36:34.350 Authenticator[94857:984290] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [nan 0; 375 60]'`

**Comment by kitasuke** [comment]
Thanks for the error report.

`PagingMenuController` does not support with only one view controller, not documented yet though.
How use case is it with only one view controller?

**Comment by kayvink** [comment]
The app displays updates on different accounts, you can add and remove accounts so the amount can vary.

**Comment by kayvink** [comment]
I fixed it, pushing a pull request in a sec.

**Comment by kitasuke** [comment]
Thanks! I'll look into it :)
