### ISSUE TITLE
add image?

### ISSUE THREAD

**Issue by losedges** [kitasuke/PagingMenuController#54]
Is it possible to use an icon instead of text?

**Comment by kitasuke** [comment]
It's not at this moment, but will be supported in the future.

**Comment by kitasuke** [comment]
Please use web font instead of image.
For example, using [GoogleMaterialIconFont](https://github.com/kitasuke/GoogleMaterialIconFont)
```swift
viewController.title = String.materialIcon(.Favorite)
option.font = UIFont.materialIconOfSize(24)
```

**Comment by edgency** [comment]
Yes! its good idea, thank you.

**Comment by losedges** [comment]
Yes! its good idea, thank you.
