### ISSUE TITLE
validateDefaultPage crash with single ViewController

### ISSUE THREAD

**Issue by kayvink** [kitasuke/PagingMenuController#56]
When using `public func setup(#viewControllers: [UIViewController], options: PagingMenuOptions)` to  update after a view controller was deleted, and at that time the previous `currentPage` was the last page in the array, the app crashes on the following function in `PagingMenuController.swift`:    

```Swift 
func moveToMenuPage(page: Int, animated: Bool)
```

Cause:  `page` is out of bounds

Proposed fix:
In `setup()` put `currentPage = self.options.defaultPage`  directly after `self.options.menuItemCount = pagingViewControllers.count` the `page` value will now be the default value, which can be set before updating.

**Comment by kitasuke** [comment]
Please use version 0.5.0.
