### ISSUE TITLE
MenuView disappears when changing to single View Controller

### ISSUE THREAD

**Issue by kayvink** [kitasuke/PagingMenuController#58]
When one of two view controllers is deleted, the MenuItemView moves to the left and loses it's horizontal line. Currently deleting the page like so:

```Swift    
internal func didDeleteAccount(index: Int) {
     
   viewControllers.removeAtIndex(index)
   pagingMenuOptions.defaultPage = viewControllers.count / 2
   pagingMenuController.setup(viewControllers: viewControllers, options: pagingMenuOptions)

        
}
```

From this
<img width="383" alt="screen shot 2015-08-05 at 17 24 01" src="https://cloud.githubusercontent.com/assets/6463146/9089711/d07f60c8-3b96-11e5-8c2b-02b580320880.png">

To this

<img width="381" alt="screen shot 2015-08-05 at 17 23 43" src="https://cloud.githubusercontent.com/assets/6463146/9089710/d049dde0-3b96-11e5-9dcb-45b9aeea3b62.png">

`centerItem` is still set to `true` but I think it probably happens because it gets confused what to center? 

Any thoughts?

**Comment by kitasuke** [comment]
Adding/Deleting menu item is not supported yet, so there might be unexpected behaviours like this. I'll check and fix such things when Adding/Deleting is supported.

**Comment by kayvink** [comment]
👍🏻

**Comment by kitasuke** [comment]
Please use version 0.5.0.
