### ISSUE TITLE
MenuView disappear

### ISSUE THREAD

**Issue by brianhei** [kitasuke/PagingMenuController#59]
I am using the latest version 0.45 and integrate the PagingMenuController to my test project.

Following is my code to add the PagingMenuController to my view controller. And I found that the menu is disappear.
let viewController1 = self.storyboard?.instantiateViewControllerWithIdentifier("ViewController1") as! ViewController1
        viewController1.title = "Menu 1"
        
        let viewController2 = self.storyboard?.instantiateViewControllerWithIdentifier("ViewController2") as! ViewController2
        viewController2.title = "Menu 2"
        
        let viewController3 = self.storyboard?.instantiateViewControllerWithIdentifier("ViewController3") as! ViewController3
        viewController3.title = "Menu 3"
        
        let viewControllers = [viewController1, viewController2, viewController3]
        
        let options = PagingMenuOptions()
        options.menuDisplayMode = PagingMenuOptions.MenuDisplayMode.SegmentedControl
        
        let pagingMenuController = self.childViewControllers.first as! PagingMenuController
        pagingMenuController.delegate = self
        pagingMenuController.setup(viewControllers: viewControllers, options: options)

![screen shot 2015-08-16 at 1 41 54 pm](https://cloud.githubusercontent.com/assets/13816317/9292193/9844f4a0-441c-11e5-8535-9348138edbc9.png)

**Comment by kitasuke** [comment]
A common mistake is that there is menu view under the navigation bar if you set inappropriate content inset. Could you tell me what content inset you set in your storyboard or code?

**Comment by brianhei** [comment]
I didn't set anything on the storyboard or code for the content inset. I will upload my config later. Thanks for your help.

**Comment by mudithsilva** [comment]
I'm a beginner of this cocoa controllers, so I did this manually, I mentioned that copy all files in pod and what should i do afterwards. When i copied all files it shows erros in copied files so please tell me what shall i do after copy files in to my project.Thanks

**Comment by brianhei** [comment]
I suggest you use CocoaPods to integrate it. 

1. Install CocoaPods 
gem install cocoapods (You may need to use sudo)

2. Create a new Xcode project. Then use terminal to your project folder and type
pod init

3. It will generate a Pod file then you can use vi or other text editor and add
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod "PagingMenuController" (to your project target)

4. Run pod install. And it will help you to do all the linking. After that it will also create a workspace to you. Then open your workspace and you can start using the PagingMenuController

**Comment by mudithsilva** [comment]
How can i do this with out using cocoa pods. Thank you !!

**Comment by kitasuke** [comment]
You can do it manually. Copy all the files in Pod/Classes directory into your project.

Could you tell me what the errors say?

**Comment by mudithsilva** [comment]
![screen shot 2015-08-21 at 9 13 21 am](https://cloud.githubusercontent.com/assets/13897053/9400900/ef89460a-47e4-11e5-8da7-4cc597ffe1e4.png)

**Comment by kitasuke** [comment]
You don't need to `import PagingMenuController` since all the files of PagingMenuController in same module.

**Comment by mudithsilva** [comment]
When remove import PagingMenueController pops out lots of erros 

![screen shot 2015-08-21 at 9 20 22 am](https://cloud.githubusercontent.com/assets/13897053/9400981/ea22d2c0-47e5-11e5-93e6-d42fd86278ef.png)

**Comment by kitasuke** [comment]
Oh this is a bug... The reason is that it doesn't import `UIKit`. I'll fix it as soon as possible.

**Comment by mudithsilva** [comment]
Thank you !! , is this fix take long time ?

**Comment by brianhei** [comment]
I think you can import UIKit manually for workaround solution

**Comment by mudithsilva** [comment]
How can i do that ? Thank you

**Comment by kitasuke** [comment]
I'll do it by this weekend, but in case you are in hurry, just add `import UIKit` into `MenuItemView.swift`, `MenuView.swift` and `PagingMenuOptions.swift`.

**Comment by mudithsilva** [comment]
Oppzzz yeah got it !!! didn't noticed that import UIKit is missing on those files. Thank you !!!

**Comment by mudithsilva** [comment]
Just another small problem, I want to active only Segmented control mode only , How can i do that

**Comment by kitasuke** [comment]
Please open as a new issue. I'll answer this there.

**Comment by mudithsilva** [comment]
About import UIKit ?

**Comment by kitasuke** [comment]
No, about how to active only Segmented control mode only!
Because it's completely different topic from this issue title.

**Comment by mudithsilva** [comment]
Ok got it Thank you !!

**Comment by kitasuke** [comment]
@brianhei Can you check if your container view's top space constraint is set to 0 for Top Layout Guide, not Superview?

**Comment by brianhei** [comment]
Thanks @kitasuke  it works after I changed the constraint.

**Comment by kitasuke** [comment]
:smile:
