### ISSUE TITLE
How to active only Segmented control or any other mode only & change color of round rect

### ISSUE THREAD

**Issue by mudithsilva** [kitasuke/PagingMenuController#61]
I want to user Segmented control and use round rect to show active page.

**Comment by kitasuke** [comment]
Set `SegmentedControl` to `menuDisplayMode` and `RoundRect` to `menuItemMode`.
You can modify `radius`, `scale` and `color` by yourself.

```swift
options.menuDisplayMode = PagingMenuOptions.MenuDisplayMode.SegmentedControl
options.menuItemMode = PagingMenuOptions.MenuItemMode.RoundRect(radius: 20, horizontalScale: 0.3, verticalScale: 0.7, selectedColor: UIColor.redColor())
```

**Comment by mudithsilva** [comment]
where should i insert this code ?

**Comment by kitasuke** [comment]
Please see [README](https://github.com/kitasuke/PagingMenuController#usage) and check usage at first!

**Comment by mudithsilva** [comment]
ok got it, Thank you !!

**Comment by kitasuke** [comment]
If you still don't know what to do, feel free to ask me :smile:

**Comment by mudithsilva** [comment]
I'm new to cocoa controllers That's why , Thank you figured it out :smiley:
