### ISSUE TITLE
how can still trigger swipable cells without triggering page view controller scroll action?

### ISSUE THREAD

**Issue by fanly** [kitasuke/PagingMenuController#62]
how can still trigger swipable cells without triggering page view controller scroll action?

**Comment by kitasuke** [comment]
No settings are needed as long as `func tableView(tableView: UITableView, canEditRowAtIndexPath indexPath: NSIndexPath) -> Bool {}` returns `true` in your view controller.

**Comment by kitasuke** [comment]
However, as you mentioned above, it's likely conflicted between both of them.
I'll fix this issue soon.

**Comment by kitasuke** [comment]
This is a known issue in general. See more detail link below.
http://stackoverflow.com/questions/11379989/swipe-to-delete-in-a-uitableview-which-is-embeded-in-a-uiscrollview

Added `scrollEnabled` option with the latest version, so set false to use swipable cell.
