### ISSUE TITLE
Disable menu item

### ISSUE THREAD

**Issue by mikle94** [kitasuke/PagingMenuController#65]
Hello, @kitasuke! You've made a great job!
I have to disable the last menuItem in pagingMenuController. Is there an ability to disable the last menuItem? I've created pageMenu with three pages ([screenshot](http://oi62.tinypic.com/i5bvc2.jpg)) but the last one should be disabled for future work. Also, is there an ability to disable user swipe to the last page? Or where I should modify the code to make it work? 
Thanks a lot!

**Comment by mikle94** [comment]
Oh, your code is perfect! It wasn't hard to do it by myself. The issue can be closed.

**Comment by alexiscrack3** [comment]
I had to do all this in order to disable menu items

class CustomViewController: PagingMenuController {
    var isScrollEnabled: Bool = true {
        didSet {
            self.scrollEnabled(isScrollEnabled)
        }
    }
    
    func scrollEnabled(_ enabled: Bool) {
        if let menuView = self.menuView, let gestureRecognizers = menuView.gestureRecognizers {
            self.gestureRecognizers(gestureRecognizers, enabled: enabled)
            
            if let containerView = menuView.subviews.first {
                for menuItemView in containerView.subviews {
                    if let gestureRecognizers = menuItemView.gestureRecognizers {
                        self.gestureRecognizers(gestureRecognizers, enabled: enabled)
                    }
                }
            }
        }
        if let view = self.view.subviews.last, let scrollView = view.subviews.last, let gestureRecognizers = scrollView.gestureRecognizers {
            self.gestureRecognizers(gestureRecognizers, enabled: enabled)
        }
    }
    
    fileprivate func gestureRecognizers(_ gestureRecognizers: [UIGestureRecognizer], enabled: Bool) {
        for gestureRecognizer in gestureRecognizers {
            gestureRecognizer.isEnabled = enabled
        }
    }
}

Is there an easier and cleaner way to do this?

**Comment by kitasuke** [comment]
I never thought disabling some menu items, but it could be an option.
