### ISSUE TITLE
Cannot pod 'PagingMenuController','~> 0.4.5'

### ISSUE THREAD

**Issue by mingming1234** [kitasuke/PagingMenuController#67]
I could not install via pod 'PagingMenuController','~> 0.4.5' for version 0.4.5.

**Comment by fatgue** [comment]
use this 

pod 'PagingMenuController' , :git => 'https://github.com/kitasuke/PagingMenuController.git', :branch => 'swift_2.0'

**Comment by kitasuke** [comment]
@mingming1234 Sorry, that was my fault...
Please try again and reopen this issue if there is still something wrong.

**Comment by mingming1234** [comment]
Yes, It works for swift 1.2. No need to install swift 2.0 branch. Thank you so much.

**Comment by kitasuke** [comment]
:smile:
