### ISSUE TITLE
Touch not recognised when only one view controller

### ISSUE THREAD

**Issue by kayvink** [kitasuke/PagingMenuController#69]
There is a tap recogniser on on of my view controllers, it works fine when there are multiple but when there are only one it stops working. `touchesBegan` is not being registered at all any more. In the 3D debugger I found the `contentView` becomes 0px wide when there is only one VC, I suspect the problem is caused somewhere in the auto layout.

I think it stops registering touches because the `View` in theory doesn't exist.  If you look at the images I've added one has the view coloured blue, the other one only has a blue line.

![screen shot 2015-08-27 at 18 06 42](https://cloud.githubusercontent.com/assets/6463146/9526040/742fa47e-4ce7-11e5-8652-15054b7f8d7c.png)

![screen shot 2015-08-27 at 18 07 36](https://cloud.githubusercontent.com/assets/6463146/9526044/788342c4-4ce7-11e5-9d8a-0890d0f7ff2e.png)

**Comment by kitasuke** [comment]
Yes, its a known issue, but again it'll be fixed when one view controller usage is supported.
I really appreciate your patience!

**Comment by kayvink** [comment]
👍🏻

Do you know where exactly it is going wrong? I could have a look at in and put in a PR. I'm having trouble laying my finger on the spot.

**Comment by kitasuke** [comment]
Yes. Thanks for your visual view debugger.

**Comment by kitasuke** [comment]
Fixed this issue. Please use version 0.4.7.
