### ISSUE TITLE
Carthage does not build version 4.6 of framework

### ISSUE THREAD

**Issue by marlowcharite** [kitasuke/PagingMenuController#76]
Hi @kitasuke, not sure if you are aware but building `PagingMenuController` framework through carthage does not build 4.6 but instead the older version of the library. I had to switch to cocoa pods to build v4.6 of the `swift_2.0` branch.

**Comment by kitasuke** [comment]
The latest version is 0.4.7, so there isn't version 4.6 yet. Did you add `github "kitasuke/PagingMenuController" == 0.4.6` in your `Cartfile` and run `carthage update`?
It works fine for me.

**Comment by marlowcharite** [comment]
I meant version 0.4.6.

**Comment by kitasuke** [comment]
I fixed this. The latest version is 0.5.0, so please use this version.

**Comment by marlowcharite** [comment]
Thanks
