### ISSUE TITLE
How to enable round rect view animation in the latest update 0.5.0?

### ISSUE THREAD

**Issue by DesmondPang** [kitasuke/PagingMenuController#81]
I have just updated the 0.5.0 and tried to change the menuItemMode to         options.menuItemMode = PagingMenuOptions.MenuItemMode.RoundRect(radius: 1, horizontalScale: 1, verticalScale: 1, selectedColor: UIColor.redColor()). There is no animation for the round rect transition. Do I need to configure other options?

**Comment by kitasuke** [comment]
Supported with 0.5.1
Notice: associated values changed on RoundRect
Please use 0.5.1 version
