### ISSUE TITLE
Tapping status bar and scrolling to top is not working for tableviews and collections

### ISSUE THREAD

**Issue by DesmondPang** [kitasuke/PagingMenuController#82]
As the tableviews and collections are placed in the container.Tapping status bar and scrolling to top is not working for them. How to solve it?

**Comment by kitasuke** [comment]
You should put `scrollsToTop = true` on your visible table view. Put `scrollsToTop = false` on the rest of table views.
See more detail below.
http://stackoverflow.com/questions/4167806/automatic-scroll-to-top-doesnt-work-in-uitableview

**Comment by patricks** [comment]
I have the same problem.
I tried the following:

- Build your PagingMenuControllerDemo 
- Set in the viewDidLoad() self.tableView.scrollsToTop = true

This also doesn't enable this feature.

**Comment by kitasuke** [comment]
Did you set `scrollsToTop` to false to the rest of table views except the visible table view?

**Comment by patricks** [comment]
No i didn't, but this is strange, ich had to disable all ```scrollsToTop``` on all other ViewControllers, also on the not visible ones.

Maybe there is a workaround?

**Comment by patricks** [comment]
I got his working with a little workaround.

- First I created a function in every ViewController, to enable / disable ```scrollsToTop``` 
- Now if I initialized the ViewControllers in the PagingMenuController is set the ```scrollsToTop``` property to ```false```on every ViewController
- Now I created a variable called ´´´currentVcIndex´´´ in the PagingMenuController class.
- Last i implemented the ´´´willMoveToMenuPage´´´ delegate methods as following:

```swift
func willMoveToMenuPage(page: Int) {
        
        let oldVC = viewControllers[currentVcIndex]
        oldVC.scrollingModeOn(false)
        
        let currentVC = viewControllers[page]
        currentVC.scrollingModeOn(true)
        
        currentVcIndex = page
    }
```

I hope this helps.

**Comment by kitasuke** [comment]
Yes, but this is not something PagingMenuController can handle. Because PagingMenuController doesn't whether subclass of UIScrollView is added or not. Even if it finds the subclass of UIScrollView, still doesn't know which view (UIWebView, UITableView or UICollectionView) is used.

However, this is a tricky spec, so I'll add how to handle it on README.
