### ISSUE TITLE
How do I lazy-load pages tabs?

### ISSUE THREAD

**Issue by wraithseeker** [kitasuke/PagingMenuController#94]
I have this issue with my app which I have about 5 pages in a View Controller. 

Each of them parses a respective JSON file from the web on startup, this takes a long time for my app to load  because it's trying to load at least 2 pages at once when I tested the app.

Is it possible for me to lazy-load the other pages or to choose when to load to the other view controllers beside the current view controller on the screen?

**Comment by kitasuke** [comment]
I'm working on this issue.

**Comment by kitasuke** [comment]
Turned out this was a bug.
I just fixed it, so please use the latest version!
