### ISSUE TITLE
How can i change from a view to the other view

### ISSUE THREAD

**Issue by santicarmo31** [kitasuke/PagingMenuController#97]
Forx example I have 2 tabs

If I'm in tab 2 and want to change to tab 1 when I press a button in tab 2.

**Comment by kitasuke** [comment]
1. Scroll content view to left or right
2. Tap either of tab 1 or tab 2

`SegmentedControl` mode might be appropriate in this situation.

**Comment by kitasuke** [comment]
Please reopen this issue if you still have no idea what to do.
